### ISSUE TITLE
Feature request: --use-ccache option

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy-helpers#104]
ccache can provide factors of several improvement in build time for astropy. Configuring ccache on every machine is a bit of a pain so I was thinking it could be nifty to have a new option ``--use-ccache`` and a corresponding ``use_ccache`` option in ``setup.cfg`` that could then indicate that we should make use of ccache wherever possible. Since we already have an ``adjust_compiler`` function it would be trivial to use this to prepend the compilation command with the ccache command.

@eteq @embray @mdboom - what do you think about this?

**Comment by embray** [comment]
astropy/astropy#4333 adds some mention of ccache to the astropy developer docs.  One could still quibble over what that documentation should say or where it should be, but that should happen over at that PR.  Won't be implementing this feature though so closing.
