### ISSUE TITLE
Inherited members always ignored in automodsumm

### ISSUE THREAD

**Issue by alexrudy** [astropy/astropy-helpers#109]
The sphinx extension ``automodsumm`` always ignores inherited class members when producing an auto summary. This is different from the default behavior of ``autosummary``. I'd like to add a configuration variable to ``automodsumm`` to be able to revert this (perhaps ``automodsumm_inherited_members``), but I wanted to bring it up here, as the behavior differs from ``autosummary``, which I find to be interesting / a possible bug.

**Comment by hamogu** [comment]
I understand why the default behavior was chosen, but it leads to odd generated doc pages in some cases, e.g. https://astropy.readthedocs.org/en/latest/api/astropy.io.ascii.Latex.html#astropy.io.ascii.Latex
It looks like that class has only a single method, so I need to go to the bases, click on that and find which methods are defined by the base class. Repeat the process, if the base class itself inherits from another class. 
Not many people will find the other methods there.
(The Latex reader is just the place where I noticed, but it's true for classes that are intended for users directly, too.)

In an ideal world, the extension would list all methods / attributes that are defined in the same package (and ignore those that are defined in eg. numpy for quantity), but a directive to enable this manually where useful would be good enough for now.
