### ISSUE TITLE
Sphinx documentation should include module constants that have docstrings

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy-helpers#117]
This apparently used to work, but seems to have stopped. See https://github.com/astropy/astropy/pull/3208#issuecomment-67406543 (refiled from https://github.com/astropy/astropy/issues/3226 per @embray's comment).

**Comment by cdeil** [comment]
We also have this issue in Gammapy that things are missing in our docs because of this bug:
https://github.com/gammapy/gammapy/issues/111#issuecomment-71041680

Anyone has the skills / time to investigate and fix this? @eteq @bsipocz ?

**Comment by astrofrog** [comment]
Also an issue for the matplotlib style dictionary in ``astropy.visualization``

**Comment by mhvk** [comment]
@embray - would you have a pointer towards where one could handle this? I am now building a new package (hopefully, affiliated at some point) and have been trying, but failed to do anything useful. I did note that `automodapi` explicitly doesn't make a summary for it. 

Strangely, constants in classes are happily shown with their docstrings.

**Comment by embray** [comment]
I really have no idea.

**Comment by mhvk** [comment]
See #198 for an idea towards a solution. Comments very welcome.

**Comment by bsipocz** [comment]
the reincarnation of #198, astropy/sphinx-automodapi#24,  got merged into ``sphinx-automodapi``, thus I'm closing this.
