### ISSUE TITLE
Sphinx oddity with doctests containing tracebacks

### ISSUE THREAD

**Issue by embray** [astropy/astropy-helpers#118]
Yet another oddity with the docs that only seem to have recently shown up in Sphinx 1.2.3 (or possibly earlier, though not before Sphinx 1.2).  See for example the last example on this page:

http://docs.astropy.org/en/stable/modeling/parameters.html#parameter-examples

Clearly the Traceback is shown twice, though the second time the exception message is also trucated to a single line.  Very odd.  Possibly a Sphinx bug more than it is something in our code but this is something to look into...

**Comment by astrofrog** [comment]
@embray - worth checking if it's possible this is related to the logger (don't *think* it is, but never know)

**Comment by embray** [comment]
I'm actually not seeing this anymore.  It's possible it was a bug in Sphinx that is since fixed.  Well, the issue has been documented, and the workaround (probably) is to upgrade Sphinx.  I'm not worried about it so long as it's not showing up in readthedocs.
