### ISSUE TITLE
Support subpackage scripts

### ISSUE THREAD

**Issue by embray** [astropy/astropy-helpers#120]
It should be possible for each subpackage to specify what console scripts they provide and the entry points (main functions) of those scripts.  See astropy/astropy#3271

**Comment by astrofrog** [comment]
I'm going to close this - I think that we should now be moving more towards standardized ways of doing this, and I think that listing entry points in ``setup.cfg`` is clean enough and simple even for a large package like astropy:

https://github.com/astropy/astropy/blob/master/setup.cfg#L29

I'm pretty sure most other packages have only one or two entry points, where using ``setup_package.py`` would be overkill.
