### ISSUE TITLE
Problem finding correct version of astropy_helpers (?)

### ISSUE THREAD

**Issue by PBarmby** [astropy/astropy-helpers#122]
I'm trying to install the development version following the instructions [here](http://docs.astropy.org/en/latest/development/workflow/get_devel_version.html). Things are failing at [step 6](http://docs.astropy.org/en/latest/development/workflow/get_devel_version.html#activate-development-astropy) like so:

    (astropy_dev_ENV)bash-3.2$ python setup.py develop
    Traceback (most recent call last):
      File "setup.py", line 21, in <module>
        from astropy_helpers.distutils_helpers import is_distutils_display_option
    ImportError: No module named distutils_helpers

I do have other versions of astropy_helpers installed -- could this be the problem? Thanks.

**Comment by embray** [comment]
Hi,

In general you shouldn't have astropy_helpers installed at all.  Try uninstalling previous versions so that the astropy source checkout will just use the one that it is shipped with.

**Comment by embray** [comment]
(And yes, this was a recent-ish (a few weeks ago) change that still continues to bite me sometimes too.)

**Comment by jehturner** [comment]
Hi Erik,

I got the same error on 2 of my Ureka build machines from "python setup.py build" (in urp). Their astropy_helpers directories are empty afterwards. A third machine worked and it looks like the difference is that it has git installed and the others haven't. Last time I checked, PyPI downloads were also failing on these machines (which is actually a good thing, as I'm trying to create a reproducible build from known local sources). I'm guessing this (no git and/or pypi) is an error condition that should be trapped in ah_bootstrap.py? I could dig into it a bit, though right now my priority is to get this working. Presumably we should be installing the right astropy_helpers tarball first for Ureka/urp.

    +++ python setup.py build
    The requested path 'astropy_helpers' for importing astropy_helpers does not exist, or does not contain a copy of the astropy_helpers package.
    Attempting download instead.
    Downloading astropy_helpers; run setup.py with the --offline option to force offline installation.
    Traceback (most recent call last):
      File "setup.py", line 21, in <module>
        from astropy_helpers.distutils_helpers import is_distutils_display_option
    ImportError: No module named distutils_helpers

Is it good form to comment on a closed request? Seems like the info. belongs in one place...

Thanks,

James.

**Comment by embray** [comment]
@jehturner It's fine by me.  Not exactly sure what's happening in your case--astropy_helpers should be bundled in the source tarball.  Let me double check that that's the case.  On the `ImportError: No module named distutils_helpers` I'm going to change that import statement in the `setup.py` to also work with the last release of astropy-helpers just so there's less trouble here.

**Comment by jehturner** [comment]
Oh, perhaps there's something wrong with how we're generating the dev source tarball (I copied it from Christine). I'll just check on that, thanks. For the upcoming release we'll be using 0.4.4 or 1.0 anyway.

**Comment by jehturner** [comment]
OK, Christine's astropy.tar.gz has an empty astropy_helpers/ directory to begin with. The STScI build must be picking the package up subsequently from git or PyPI. I'll check with her on how that tarball is generated. Thanks.

**Comment by embray** [comment]
Should just use the one on PyPI.  I checked it and it's good.
