### ISSUE TITLE
Consider renaming astropy-helpers in the long term

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy-helpers#125]
Glue (http://glueviz.org) is an example of a non-astro-specific package where I think it would be nice to make use of astropy-helpers. We had previously discussed that in the long term we might consider renaming astropy-helpers to something more generic so that it can be used by non-astro packages (of course it _can_ be used already, but having 'astro' in the name can make it sound like it is astro-specific). So this issue is just to start a conversation about whether we should consider renaming astropy-helpers to something else in future? (e.g. `setup-helpers`?)

**Comment by pllim** [comment]
`setup-helpers` sound too cryptic to me. Isn't it still geared towards astronomy community?

**Comment by embray** [comment]
@pllim There's not much about it geared toward the astronomy community.  But I agree `setup-helpers` is cryptic.

I'm not in any hurry to do this though.  This very much falls under my much talked about successor to d2to1, into which I hope to incorporate a lot of what's been developed for astropy-helpers.  It's just not something I've had much luck having time to work on (see https://github.com/embray/setup.cfg)

**Comment by Cadair** [comment]
I would like to kick this again, I know that this is doing the job for us at the moment, but with the expection of the astropy sphinx theme (which should not be in here anyway) there is nothing astro-specific in here.

This is a really nice tool, and it should be named to encourage use from other people.

**Comment by alexrudy** [comment]
I'm 👍 on this as well, and I'd like to suggest that we move some of the things in astropy which are really helpers over here, like much of https://github.com/astropy/astropy/tree/master/astropy/tests

Are there objections to working on this other than the undue burden on core devs who are working on other things? I find this package super useful, and would love, even fi the name doesn't change, to divorce it from the hard astropy dependency. I'm happy to put the effort in there.

**Comment by embray** [comment]
No problem with renaming, but the idea of putting the tests stuff in astropy-helpers has been brought up before and I still think it's not a good idea, but it requires astropy-helpers to be installed in site-packages in order to run installed tests.  I'd rather the tests module be a package unto itself if it were ever split out.

**Comment by bsipocz** [comment]
I'm closing this as a "won't fix".
