### ISSUE TITLE
Validate that the package's version string is valid

### ISSUE THREAD

**Issue by embray** [astropy/astropy-helpers#138]
astropy-helpers should do something to confirm that the package's version is valid (preferably conformant to PEP 440, but at least parseable if nothing else.

This came up because I had a test package in which the version was accidentally a float instead of a string and it led to all sorts of hard to debug badness :)

**Comment by astrofrog** [comment]
I'm going to close this - [APE 17](https://github.com/astropy/astropy-APEs/blob/master/APE17.rst) recommends moving to using setuptools_scm for managing the version, and the issue here isn't really a bug as such, just a validation feature that would be nice to have but isn't critical.
