### ISSUE TITLE
Version parsing broken with setuptools 8.0

### ISSUE THREAD

**Issue by embray** [astropy/astropy-helpers#162]
See astropy/astropy#3745.  This is an issue that only affects users with some older versions of setuptools before the recent version parsing refactoring.  But 8.0 isn't _that_ old either--probably less than a year.  astropy-helpers strives to work with as many versions of setuptools as possible since users tend to have many arbitrary versions scattered about (myself included).

**Comment by bsipocz** [comment]
Do we still need a fix this for such old setuptools?

**Comment by bsipocz** [comment]
Closing now, as we probably won't fix this.
