### ISSUE TITLE
Should sphinx be an install requirement?

### ISSUE THREAD

**Issue by mwcraig** [astropy/astropy-helpers#166]
In working on building conda package I noticed than one of the subpackage imports fails if sphinx is not installed: `import astropy_helpers.sphinx.ext` raises an `ImportError` when it hits `from .numpydoc import setup` because `numpydoc` imports sphinx at https://github.com/astropy/astropy-helpers/blob/master/astropy_helpers/sphinx/ext/numpydoc.py#L21

I'm not sure this is really an issue...presumably anyone importing `astropy_helpers.sphinx.ext` will already have `sphinx` installed, but encountered this in one of the import tests that conda runs when building.

**Comment by astrofrog** [comment]
@mwcraig - I don't know if we need to create a conda package for astropy-helpers since it should never be a run-time dependency. Is it currently required by any package at runtime?

**Comment by mwcraig** [comment]
@astrofrog -- Not at run time, no, but sncosmo  needs it (for now) because `conda build` turns off downloading [1] from setuptools while building and sncosmo relies on `ah_bootstrap.py` to get astropy-helpers. 

Once there is a new release of sncosmo it will be buildable via `bdist_conda`, which doesn't shut down downloads.

In addition, there is a use-case for astropy-helpers as a standalone: using its sphinx extensions. That doesn't make it a runtime dependency, but it could be a legitimate doc dependency.

[1] https://groups.google.com/a/continuum.io/forum/#!topic/conda/ZKdP5BujriA

**Comment by embray** [comment]
It will be problematic if Sphinx is an install requirement, since astropy-helpers is also used for build/installation and most users don't need to build the docs.  It could be added as an optional requirement (via extras), which I think I've considered before and just haven't done.

**Comment by embray** [comment]
(Btw if at the very least `import astropy.sphinx` results in an unhelpful import error there can still be a check for Sphinx installation in the module init.  But it is not a requirement.)

**Comment by mwcraig** [comment]
There is an easy enough workaround for building astropy-helpers -- I've got a recipe for it and can just skip those import tests (turns out `import astropy_helpers.sphinx.ext.tests` fails unless `pytest` is installed, of the same variety of failure as the sphinx import).

**Comment by mwcraig** [comment]
I could put astropy-helpers on the astropy-ci-extras channel if we don't want it in the channel for affiliates.

**Comment by embray** [comment]
I don't know, that's up to you.  I don't pay attention to any of the anaconda stuff--as far as I'm concerned it's upstream packaging.

**Comment by embray** [comment]
Though as a general point you shouldn't have to install Sphinx (and all its dependencies) just to install astropy-helpers.

**Comment by mwcraig** [comment]
It sounds like the answer to the question in the issue is "No" (I agree with you), so I'm closing :)

**Comment by astrofrog** [comment]
@mwcraig - by the way, when you build conda packages, you should use ``--offline --no-git`` to force the installer to use the bundled astropy-helpers.

**Comment by mwcraig** [comment]
Unfortunately, sncosmo didn't bundle astropy-helpers so --offline can't work, but there is another combination of arguments that does, so it is building now.
