### ISSUE TITLE
Add support for setup_requires that are only used in development

### ISSUE THREAD

**Issue by embray** [astropy/astropy-helpers#167]
Inspired by astropy/astropy#3229, it would be useful to have an easy way to specify build requirements in `setup_requires` that are used when building the package from a VCS checkout, but that are _stripped_ from source release tarballs.  

For Astropy itself this includes Jinja2 and Cython--i.e. any packages that are required to _generate_ files that will be included in the source distribution, but are not needed for building the source distribution since those files are already generated and packaged with it.

**Comment by embray** [comment]
One possible way to handle this, and similar issues, might be to have two separate setup.cfg files.  The default setup.cfg would be used for source checkouts.  But when writing a source distribution it would be overwritten with a different setup.cfg for source dists.  I think Numpy has an approach somewhat like this.

**Comment by astrofrog** [comment]
This is no longer relevant given the plan to migrate to using ``pyproject.toml`` as described in APE 17
