### ISSUE TITLE
Better package for graphviz?

### ISSUE THREAD

**Issue by embray** [astropy/astropy-helpers#176]
Lately I've had fairly frequent build failures on Windows due to the Chocolatey package we're using for graphviz, which downloads from graphviz.org on every install.  However, graphviz.org appears to be somewhat unreliable, resulting in timeouts, and thus botched builds.

I'm a little surprised the file isn't just cached by AppVeyor, but who knows how aggressively they cache.

So I wanted to see if we could point Chocolatey to a better URL for graphviz, perhaps a download we would just host ourselves.  According to the Chocolatey folks that is [not possible at this time](https://chocolatey.org/packages/graphviz.portable#comment-2151525358), but we could make our own copy of the package, with our own download URL, and point `choco install` to our custom package, which would be fine I guess.

**Comment by astrofrog** [comment]
This doesn't seem to be a problem anymore, so I'd suggest closing this.

**Comment by bsipocz** [comment]
Closing now, but we can reopen if it's becomes a problem again.
