### ISSUE TITLE
bootstrap-astropy.css messes up line numbering on sphinx code blocks

### ISSUE THREAD

**Issue by RiceMunk** [astropy/astropy-helpers#179]
Currently working on the documentation for something I'm trying to get released as an astropy affiliated package, and I found a problem with how numbered code blocks are rendered using the astropy sphinx css stuff.

Here's a screenshot of what happens (at least with Chrome and Firefox) if I try to make a line-numbered code block in sphinx (using the code-block::-markup):
![sphinx_codeblock_wrong](https://cloud.githubusercontent.com/assets/401690/9363229/16c40582-469d-11e5-9116-a4457e23ea43.png)

The line numbering on that is not very useful, so it's a problem for my attempt at writing examples.

After a while of scrathing my head and learning how the element inspection thingy on Chrome works, I found out that this is because of something in bootstrap-astropy.css. Turns out that, for reasons I don't really understand, the line "white-space: pre-wrap;" in the pre-block (line 153 in bootstrap-astropy.css) is causing this problem. If I remove that line from the css, I get something a bit better-looking:
![sphinx_codeblock_lesswrong](https://cloud.githubusercontent.com/assets/401690/9363326/c3549d70-469d-11e5-8862-512ac2b74997.png)

Gonna modify the css in the thingy I'm working on to not cause the line numbering issue, but I figured you people would wanna know about this as well.

**Comment by embray** [comment]
That's odd. I think none of the Astropy docs use line numbering, so it hadn't come up before.  I'm not sure why this happens either--thanks for the report.

**Comment by RiceMunk** [comment]
No problem. I went ahead and made a pull request for the quick fix I made.

Not sure if that's the best way of going about getting rid of this issue but there you have it. See pull request #180.

**Comment by embray** [comment]
Fixed by #180--thanks @RiceMunk
