### ISSUE TITLE
Have option to emit Sphinx warnings if no docstring is found

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy-helpers#195]
I originally implemented this in https://github.com/astropy/astropy-helpers/pull/103 but in the mean time, we've changed to no longer use the `AstropyAutosummary` class. I've opened this issue to keep track of this wishlist item nevertheless. Maybe we should propose this option in the upstream autosummary?

**Comment by embray** [comment]
I think submitting a PR to sphinx would be the best approach.  In the meantime there's no reason we can't switch back to using a subclass, though I'd say only if it's easy to implement this functionality in a subclass in some way that *doesn't* require copying any code from the base implementation (the fact that we were doing this previously ran afoul of updates to Sphinx).

**Comment by astrofrog** [comment]
This issue has been moved to https://github.com/astropy/sphinx-automodapi/issues/45
