### ISSUE TITLE
Generating methods summary in API docs is broken

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy-helpers#200]
I wonder whether anyone know how to fix the generation method summary of classes in the html API docs? 
It seems to be working in the ``rst`` generating step, but I couldn't spot where it went wrong after that.

in ``astropy.table.Table.rst``:

```
   .. rubric:: Attributes Summary

   .. autosummary::
   
      ~Table.ColumnClass
      ~Table.colnames
      ~Table.dtype
      ~Table.groups
      ~Table.has_mixin_columns
      ~Table.iloc
      ~Table.indices
      ~Table.info
      ~Table.loc
      ~Table.mask
      ~Table.masked

   
   

   
   

   .. rubric:: Methods Summary

   .. autosummary::
   
      ~Table.add_column
      ~Table.add_columns
      ~Table.add_index
      ~Table.add_row
      ~Table.argsort
      ~Table.as_array
      ~Table.convert_bytestring_to_unicode
      ~Table.convert_unicode_to_bytestring
      ~Table.copy
      ~Table.field
      ~Table.filled
      ~Table.from_pandas
      ~Table.group_by
      ~Table.index_column
      ~Table.index_mode
      ~Table.insert_row
      ~Table.keep_columns
      ~Table.keys
      ~Table.more
      ~Table.pformat
      ~Table.pprint
      ~Table.read
      ~Table.remove_column
      ~Table.remove_columns
      ~Table.remove_indices
      ~Table.remove_row
      ~Table.remove_rows
      ~Table.rename_column
      ~Table.replace_column
      ~Table.reverse
      ~Table.show_in_browser
      ~Table.show_in_notebook
      ~Table.sort
      ~Table.to_pandas
      ~Table.write

   
   

   
   

   .. rubric:: Attributes Documentation
```

But the the generated pages doesn't have a single method summary entry:
http://docs.astropy.org/en/latest/api/astropy.table.Table.html#astropy.table.Table

![screen shot 2015-10-31 at 18 11 50](https://cloud.githubusercontent.com/assets/6788290/10865184/7db6ca26-7ffb-11e5-89df-01cf09fd3fc7.png)

**Comment by eteq** [comment]
This looks to be the same as #172, right @bsipocz ?  There's a fix in progress there, so I'm going to close this as a dupe (but if there's more to it, feel free to re-open!)

**Comment by bsipocz** [comment]
@eteq - yes, it indeed looks like a duplicate. I run into this with an affiliate, but it's funny I choose ``Table`` as an example, just as in #172 and yet didn't find that issue.
