### ISSUE TITLE
pip install spawns a lot of build_ext processes

### ISSUE THREAD

**Issue by saimn** [astropy/astropy-helpers#207]
When trying to run astropy's tests with tox, I got into some weird issue with I can reproduce simply with:
```
$ python setup.py sdist
$ pip install dist/astropy-1.1.dev14145.tar.gz
```
The `pip install` command will then spawn continuously `build_ext` processes until my system dies /o\ (See screenshot below). I guess this can be related to astropy's build system which detect than I run pip install with a development version, but the issue also happens if I run the pip install in a fresh virtualenv with only Numpy installed (no Cython or Jinja2).

![2015-11-25-152956_4800x1800_scrot](https://cloud.githubusercontent.com/assets/311639/11419547/748008a0-9428-11e5-8f8c-cf7367f5521a.png)

**Comment by embray** [comment]
Yikes!  That's odd. I wonder if this is an issue with tox.  I use tox and have not run into this, but I also haven't upgraded it in a while.

**Comment by embray** [comment]
But wait, you're saying you reproduced this even without tox, right?

**Comment by embray** [comment]
Well, the good news is I wasn't able to immediately reproduce this.  The bad news is, I wasn't able to immediately reproduce this so I have no idea what's going on.

For starters, please provide the output of:
```
$ python -c 'import sys; print(sys.version)'
$ pip --version
$ python -c 'import wheel; print(wheel.__version__)'
```

**Comment by embray** [comment]
Okay, I think this almost certainly has to have something to do with this: https://github.com/astropy/astropy/blob/v1.1rc1/astropy/__init__.py#L187

In which case this isn't anything to do with astropy-helpers.  Strange that I can't reproduce it though.  Would still be good to know pip version, etc.

**Comment by embray** [comment]
Oh wait, maybe this does have to do with astropy-helpers.  What version of astropy-helpers is it using when you install?  When you created the tarball what version of astropy-helpers was bundled with it?   It's probably out of date.

**Comment by saimn** [comment]
> But wait, you're saying you reproduced this even without tox, right?

Yes, just with `python setup.py sdist` and then `pip install dist/astropy-1.1.dev14145.tar.gz`

```
~/lib/astropy master* 17s
(test)❯ pip list -l
numpy (1.10.1)
pip (7.1.2)
setuptools (18.2)
wheel (0.24.0)

~/lib/astropy master*
(test)❯ git describe
v1.0rc1-2387-g0b755fa

t~/lib/astropy master*
(test)❯ git submodule
 1ac98cd9682acc96fbb03bcda2d47cd720de3ce7 astropy_helpers (v1.1rc1)

```
astropy_helpers is up to date and I can reproduce with it. I will try with the patch from your PR.

**Comment by saimn** [comment]
Same after upgrading setuptools and wheel, git clean -fxd, and recompiling.

Oh wait, when trying to build and install with your PR, I got a weird error with astropy_helpers:
```
Processing ./dist/astropy-1.1.dev14154.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/simon/pip-2Ym7uD-build/setup.py", line 52, in <module>
        package_info = get_package_info()
      File "/tmp/simon/pip-2Ym7uD-build/.eggs/astropy_helpers-0.4.8-py2.7.egg/astropy_helpers/setup_helpers.py", line 1096, in get_package_info
        for setuppkg in iter_setup_packages(srcdir, packages):
      File "/tmp/simon/pip-2Ym7uD-build/.eggs/astropy_helpers-0.4.8-py2.7.egg/astropy_helpers/setup_helpers.py", line 1168, in iter_setup_packages
        module = import_file(setup_package)
      File "/tmp/simon/pip-2Ym7uD-build/.eggs/astropy_helpers-0.4.8-py2.7.egg/astropy_helpers/setup_helpers.py", line 1350, in import_file
        return imp.load_module(name, fd, filename, ('.py', 'U', 1))
      File "astropy/modeling/setup_package.py", line 14, in <module>
        wcs_setup_package = utils.import_file(join('astropy', 'wcs', 'setup_package.py'))
      File "/tmp/simon/pip-2Ym7uD-build/.eggs/astropy_helpers-0.4.8-py2.7.egg/astropy_helpers/utils.py", line 169, in import_file
        if name is None:
    UnboundLocalError: local variable 'name' referenced before assignment
```
It seems I was using an old version of astropy_helpers via the .egg-info stuff (but I don't know where the astropy_helpers-0.4.8-py2.7.egg came from ??) :
```
(test)❯ l astropy_helpers/astropy_helpers.egg-info
total 20K
-rw-r--r-- 1 simon    1 28 nov.   2014 dependency_links.txt
-rw-r--r-- 1 simon    1 28 nov.   2014 not-zip-safe
-rw-r--r-- 1 simon 2,8K 28 nov.   2014 PKG-INFO
-rw-r--r-- 1 simon 2,8K 28 nov.   2014 SOURCES.txt
-rw-r--r-- 1 simon   16 28 nov.   2014 top_level.txt
```

After cleaning this `astropy_helpers/astropy_helpers.egg-info` directory, I can now pip install correctly, with master and with your PR. But I'm still confused by this error: first git clean didn't remove this directory, second why was the .egg-info out of date ? Now that I have deleted it, it has been created again, but I thought astropy_helpers was not installed ?

**Comment by embray** [comment]
That I can't help you with.  No way of knowing what exactly you did, but it sounds like this is fine now.

**Comment by embray** [comment]
Oh, astropy_helpers.egg-info is always created--that's a normal part of package initialization.  The .egg-info directory for a Python distribution (now also called .dist-info, though setuptools still calls it .egg-info by default for historical reasons) contains all the metadata about the package.  It is used, for example, by the `pkg_resources` module to discover information about installed distributions.  In the case of astropy_helpers, it gets created in the ah_bootstrap.py script so that the astropy_helpers package can be found via the submodule.  

`git clean` from the root of your repo wouldn't normally remove it, since it's in a submodule.  But you shouldn't have to delete it either.  I don't think the .egg-info dir has anything to do with your problem.

**Comment by saimn** [comment]
Hmm yes, hard to say what happened, but it is fine now. Thanks for your help !
