### ISSUE TITLE
Improvements to edit_on_github extension

### ISSUE THREAD

**Issue by embray** [astropy/astropy-helpers#211]
In https://github.com/astropy/astropy/issues/4361#issuecomment-167673551 I suggested a few fixes to the edit_on_github Sphinx extension that might be worth making:
- [ ] If the `doctree` argument passed to `html_page_content` is `None`, this implies an HTML page that was not generated from an actual rst document.  Usually this implies that there is no page to edit on GitHub, though I suppose a static HTML page that lives in the repository is also possible.  In either case, the case of `doctree is None` should be handled in some appropriate way.  Currently if `doctree is None` for a page that is _not_ skipped, the extension crashes.
- [ ] The default for `edit_on_github_skip_regex` should be updated, probably to include `api.*` pages for compatibility with automodapi.  Better yet, maybe the extension can check if automodapi is being used, and automatically skip anything that starts with the value for the `automodapi_toctreedirnm` config option used by automodapi.

**Comment by astrofrog** [comment]
I've moved this issue to https://github.com/astropy/sphinx-astropy/issues/6
