### ISSUE TITLE
Figure out why egg-info needs to be included

### ISSUE THREAD

**Issue by eteq** [astropy/astropy-helpers#221]
While working on astropy/astropy#4682, @astrofrog and I were surprised to find that the `astropy_helpers.egg-info` had to be included in the base package's `MANIFEST.in` for the helpers offline machinery to work.  Without that, a `The requested path 'astropy_helpers' for importing astropy_helpers does not exist, or does not contain a copy of the astropy_helpers package.` came up and the build fails if you don't have internet (or use `--offline`).  This seems surprising and counter-intuitive.

@embray, do you have any insight about this?

**Comment by eatdust** [comment]
Related to this, if one removes the egg files, the main astropy package does not compile any more due to that very same error.

Within astropy source file,  in: `ah_bootstrap.py`

``
def _directory_import(self):
``      

This function is checking if "setup.py" is provided within astropy_helpers/. If not found, you get the error. After adding the setup.py (from astropy_helpers branches) the eggs are correctly generated by the main astropy setup.py and no longer required. So either this function should be corrected accordingly, of the setup.py file provided.

Cheers.

**Comment by embray** [comment]
Bizarre--I just saw this ticket.  I believe @eatdust is on the mark.  I think the main problem is that you're excluding the `setup.py` for `astropy_helpers` from the source tarball.  I would fix that, and remove the needless `.egg-info` stuff from the `MANIFEST.in`.

---

There's a *lot* about astropy_helpers and how it is used that needs to be reworked.  Almost all the boilerplate that uses it in Astropy's setup.py should go away, for example.  It's a complete mess (though it does look a little better now than it used to).  Before I departed (more or less) from the project it was my intention to clean that up but it was "working" so it sort of kept getting pushed down the list.  I wonder if I'll ever have time to revisit that...

**Comment by pllim** [comment]
There were talks to reduce helpers into a single file and get rid of it as a submodule entirely...

**Comment by bsipocz** [comment]
> There were talks to reduce helpers into a single file and get rid of it as a submodule entirely...

@pllim - do you think there would be enough interest to actually get this done as a sprint during the coordination meeting? Would you think we can add it to the provisory agenda and look for reactions?

**Comment by epassaro** [comment]
Hi @astrofrog. After working a month on our conda-forge package TARDIS, I still I can't make it work when using a GitHub release tar.gz file (no PyPI package).

I'm using the same `script` command in _meta.yaml_, and added the same astropy_helpers lines in [MANIFEST.in](https://github.com/epassaro/tardis/blob/conda-forge/MANIFEST.in) that you are using in Astroquery package.

Do you have any idea why it's not working for us?
