### ISSUE TITLE
Figure out why the travis tests are failing on the "eva" version name

### ISSUE THREAD

**Issue by eteq** [astropy/astropy-helpers#222]
About half of the helpers' tests are currently failing due to a few instances of ``SystemExit: error: Invalid distribution name or version syntax: -eva--1.0.dev1``.  E.g., https://travis-ci.org/astropy/astropy-helpers/builds/115207264

It doesn't seem to be affecting the functionality, so maybe it's a change in how version parsing works?  @astrofrog, I think you were going to look at this?  Or maybe @embray has some insight?

**Comment by bsipocz** [comment]
@eteq - This is down to the new v20.x setuptools. Tests pass with older versions. 
Even though we test against the dev version, the latest test that run and passed was against setuptools==19.8.dev0 in https://travis-ci.org/astropy/astropy-helpers/jobs/107074804.

So while this doesn't solve the issue I suggest to limit the setuptools version number until someone figures the solution out, thus we still see other failures genuine to a given PR. (And also add an extra one or two builds with the "stable" setuptools to the allowed failures as a reminder that something needs to be fixed).

We may also consider limiting the sphinx version number until both parts of #224 is solved.

Should I open a PR with these?

**Comment by eteq** [comment]
Alright, this is ameliorated by #225.  

But @bsipocz, do you have any idea what the underlying problem is? Or @astrofrog or @embray?

**Comment by bsipocz** [comment]
Nope, sadly I don't have a clue.

I think I would do it with the brute force approach and start diffing setuptools 19.8 and 20.1. But I won't have time for it any time soon (as both the helpers and setuptools seem too complex, so I know I would run into stupid deadends first).

**Comment by astrofrog** [comment]
I'm git bisecting right now.

**Comment by astrofrog** [comment]
The first failing commit in setuptools is https://github.com/pypa/setuptools/commit/a718819d2849196e902808301c9a95724510c5c1

**Comment by astrofrog** [comment]
I think it might just be that the test package we use starts and ends with an underscore? (``_eva_``)

**Comment by astrofrog** [comment]
Confirmed: changing ``_eva_`` to ``eva`` fixes it.

**Comment by astrofrog** [comment]
Now the question is whether this is a setuptools bug, but I don't have time to investigate that right now...
