### ISSUE TITLE
Undo #229 once sphinx 1.4.2 is out

### ISSUE THREAD

**Issue by eteq** [astropy/astropy-helpers#231]
As discussed in a bit more detail in #229 and #227, there's been a spurious warning due to us overriding some sphinx behavior.  #229 implements a hacky work-around, but sphinx-doc/sphinx#2451 describes a change to sphinx that lets us do this in a much less hacky manner.  So once sphinx 1.4.2 is released, we should use that and remove the hack from #229.

cc @bsipocz

**Comment by bsipocz** [comment]
Sphinx 1.4.3 is already out, what do you think @eteq should we remove #229? (Meaning that packages using astropy-helpers will need sphinx <1.4 or >=1.4.2 to return a clean sphinx build).

**Comment by bsipocz** [comment]
Remind me to do this before v1.3

**Comment by bsipocz** [comment]
The workaround of #229 was reworked in ae134527936c5184d96abc9e96939e64488bea11 so I'm closing this now.
