### ISSUE TITLE
Warning from numpydoc doesn't trigger Sphinx fail.

### ISSUE THREAD

**Issue by MSeifert04** [astropy/astropy-helpers#233]
The warning emitted in [NumpyDocString](https://github.com/astropy/astropy-helpers/blob/master/astropy_helpers/sphinx/ext/docscrape.py#L120) isn't catched by sphinx so it passes the travis CI checks - though the section isn't even rendered in the output. I think these warnings should fail sphinx-builds.

A bit more information (not much) can be found in a recent PR to fix such a warning: https://github.com/astropy/astropy/pull/4852

**Comment by astrofrog** [comment]
Can someone investigate this to see if it is still an issue?

**Comment by bsipocz** [comment]
This should have been fixed on the numpydoc side,  at least we had tons of failures when they switched on failing on these warnings since 0.7?. 
See e.g. https://github.com/numpy/numpydoc/issues/115 and some of the v2.0.2 helpers update PRs.
