### ISSUE TITLE
Move the sphinx extensions in to a seperate installable package

### ISSUE THREAD

**Issue by Cadair** [astropy/astropy-helpers#234]
I often find myself going to recommend `automodapi` to people but then realise that they would need to pick up the astropy-helpers submodule and all the stuff to really use them, is there any reason why moving them to a seperate package would be unwelcome?

`automodapi` really is lovely and it seems a shame to keep it hidden away in here.

**Comment by Cadair** [comment]
same goes for the theme while we are at it...

**Comment by bsipocz** [comment]
(well, you can use the same argument for basically everything in astropy-helpers, e.g. I love how the testing is set up, and the extra doctest decorators).

**Comment by Cadair** [comment]
but not everything, the actual setup.py machinery needs to be in a submodule, and that's cool. 

Isn't the test runner in astropy now anyway?

Maybe the doctest stuff should go somewhere else as well?! I don't know much about it.

**Comment by Cadair** [comment]
This is an example of the theme as a standalone package: https://github.com/Cadair/astropy-sphinx-theme

**Comment by astrofrog** [comment]
@eteq and I had a chat about this and we agree it'd be worth trying this.

We should start with automodapi as an example. I think it makes sense to try and create a package ``sphinx-automodapi`` or something like that that includes:

* astropyautosummary (actually do we still need that or is that obsolete?)
* automodapi
* automodsumm
* smart_resolver (since it's basically related to the API docs)
* autodoc_enhancements maybe? (since that seems related?)

and we should include the relevant tests.

Would anyone be interested in doing the work of setting up that package? (@Cadair or @bsipocz or both?) If so I can create a repo in the astropy organization. Once we have that in place, I can test it out with a couple of non-astro packages I have to see if it works, and we can then make a decision whether to go ahead with this.

Note that we should also add sphinx docs in the process to describe how to use this sphinx extension.

**Comment by pllim** [comment]
c/c @justincely since he was just playing with a similar idea recently.

**Comment by bsipocz** [comment]
@astrofrog - in general I'm interesed in this so keep me it the loop, but
can't commit to do much work in the next few weeks as I need to finish up a
few other things.

**Comment by saimn** [comment]
:+1: for this. I use automodapi for a package without astropy-helpers, and having a pip-installable package would make things easier (I had to modify a few things, like the relative imports).

    astropyautosummary (actually do we still need that or is that obsolete?)

It is mainly for Sphinx < 1.2 and there is also a [patch](https://github.com/astropy/astropy-helpers/blob/master/astropy_helpers/sphinx/ext/astropyautosummary.py#L115) for Sphinx 1.3.2

    automodapi
    automodsumm
    smart_resolver (since it's basically related to the API docs)
    autodoc_enhancements maybe? (since that seems related?)

\+ the `utils.py` file which is common to automodapi/automodsumm/astropyautosummary

**Comment by justincely** [comment]
also very interested in this - there are a number of people that like many aspects of the astropy-helper ecosystem, but want to avoid others (like the setup stuff or the build system).  Allowing these projects to still use the templates and things sounds like a great idea.  

Same thing with the audomodapi - i can think of a few projects that would love to use that extension, but installing the entire astropy-helper suite is a little heavy-handed.  I'm afraid I have no experience with the extensions, so will be of little help in separating that out.

**Comment by astrofrog** [comment]
Well, if no one else is going to work on this, I'm going to work on it on the ✈️ today!

**Comment by astrofrog** [comment]
Here goes:

GitHub repo: https://github.com/astropy/sphinx-automodapi

RTD: http://sphinx-automodapi.readthedocs.io/en/latest/

In the process, I found a couple of minor bugs (but doesn't affect Astropy). Test coverage is not great yet, but that's the same as here (just copied over the tests). I don't have much more time to work on it for now, but it's a starting point.

**Comment by pllim** [comment]
Can we close this now?

**Comment by Cadair** [comment]
If you want to close this we should create a new one for moving out the theme as well.

**Comment by bsipocz** [comment]
@Cadair - Could you add a few more details of why moving the theme out of the helpers is useful? I think it would be useful to provide a unified theme for the affiliates (like we currently do, but we also already discussed that there are quite a few issues with the current on), but I don't see the need to maintain it in a separate repo. 
Any non affiliated package can use sphnix-theme, but I wonder whether there is any package out there that opt out of the helpers yet still want to use the astropy branded theme...

**Comment by Cadair** [comment]
a package which is just documentation might want to use it, like for instance the cookiecutter package template. It wont have any actual installable code so doesn't need helpers, but will have docs, so would want the theme.

**Comment by bsipocz** [comment]
Well, I think the cookiecutter template will need everything opt in for the docs to have a full API docs. Also, I think the overhead and extra complexity of maintaining yet another repo isn't worth it for just that singe case.
@astrofrog, @eteq?

**Comment by Cadair** [comment]
@bsipocz by the template I meant the documentation for the template rather than the template itself.
I am not sure there is much extra overhead for the theme, it's not like it's updated often XD

**Comment by bsipocz** [comment]
Well, the is already pile of confusion around the helpers vs template, I'm -1 on adding anything more to it. The docs for the template will probably live in either in that repo or in astropy core, so I still don't see the point.

**Comment by eteq** [comment]
Definitely -1 on another repo.  Part of the reason why it's not updated often is because this is all so confusing.

Always remember, the typical user *and* typical contributor is not the sort of people leaving comments here ;)

**Comment by Cadair** [comment]
I don't really agree with that, it's not like we are talking about moving this out of the core package into it's own thing. It's already in another repo, if anything I think putting it in a repo that clearly says "sphinx theme" in the name will make it *easier* for people to find it if they want to tweak something with the theme. As it is at the moment you have to know that the astropy sphinx theme is hiding in here (which is not easy to work out by looking at `astropy/doc/conf.py`) before you know where to submit a PR.

**Comment by eteq** [comment]
Actually, wait, is there any reason why the theme can't go into sphinx-automodapi? Wouldn't that resolve both problems?  Or is it that we don't want "Astropy stuff" in the `sphinx-automodapi` repo?

**Comment by bsipocz** [comment]
@Cadair - I still don't see your point. More repo means more confusion and more maintenance overhead. The theme is something that needs some more work on it, but other than that it's quite a part of an astropy-themed/branded package template. Yet another repo wouldn't solve any of those issues imo, only add extra maintanence burden and confusion.

**Comment by bsipocz** [comment]
@eteq - Yes, I think that was the main reason to factor that out, to have an astropy unrelated package, that may be end up upstream (in sphinx) at one point? For that it made perfect sense to have a separate repo.

**Comment by Cadair** [comment]
I would not put the theme in automodapi that's even more confusing.

Seeing how I will not be the one dealing with it, I will let this go. I will make a PR to make it nice and easy to use the theme from a pip installed version of astropy-helpers which solves my particular problem with the cookiecutter template.

**Comment by bsipocz** [comment]
@Cadair - I think now I got the original issue. Why don't you just have the helpers in the cookicutter template? The need for the template is a good enough reason to have it I think and you don't need to hack with an installed version then.

**Comment by Cadair** [comment]
All I would need the submodule for in the (root of the) template repo is the theme, which is confusing to those who come to look at it.

**Comment by bsipocz** [comment]
But pedagogically it's fine, as the template they get out of the cookiecutter will have get the same theme the same way.

**Comment by Cadair** [comment]
That is true.

However, @eteq  and maybe yourself have already been confused about the actual template moving to a sub directory, I want to minimise that confusion as much as possible.

**Comment by Cadair** [comment]
#290

**Comment by embray** [comment]
I think it would be good to have the Astropy theme in a separate repo / project.  Then astropy-helpers and/or astropy itself or the package-template can just add it as another dependency.  A good reason for separating it would be that something like a Sphinx theme, what with constantly shifting requirements in HTML, CSS, browser support, etc. requires occasional updates that have nothing to do with the other aspects of astropy-helpers (installation support, etc.).  So I think *more* modularity here is a win.  It also makes it easier for other projects to fork and customize the theme without having to extract it from astropy-helpers first (as @Cadair has already done).

**Comment by embray** [comment]
(I agree that the astropy theme and the other Sphinx extensions should be separate though)
