### ISSUE TITLE
Intersphinx: collections (python2) -> collections.abc (python3)

### ISSUE THREAD

**Issue by MSeifert04** [astropy/astropy-helpers#237]
Is it possible to setup an intersphinx mapping that links the python3 ``collections.abc`` as well as the python2 ``collections`` correctly?

For example ``collections.Mapping`` (py2) is now ``collections.abc.Mapping`` (py3). But the not-abcs like ``collections.OrderedDict`` remained in the ``collections`` namespace.

**Comment by bsipocz** [comment]
Ideally it should be fine if the code works using this as ``collections.Mapping`` for both versions. Did you see sphinx warnings when building the docs?

**Comment by bsipocz** [comment]
OK, now I see it locally. I think this kind of things should have dealt with in the official python interpshinx, but since it isn't I'll add it to our local one. Thanks @MSeifert04 for spotting it.

**Comment by astrofrog** [comment]
@bsipocz - can this be closed?

**Comment by bsipocz** [comment]
@astrofrog - absolutely
