### ISSUE TITLE
Travis tests fail on astropy=Development

### ISSUE THREAD

**Issue by cmccully** [astropy/astropy-helpers#242]
I was not sure where this issue should be posted (here or github.com/astropy/package-template). 
I use the package template to run travis tests for github.com/LCOGT/banzai. One of the travis tests is failing on astropy=DEVELOPMENT. It appears to be installing a pretty old version of numpy before giving this error:
in _execfile
      File "/tmp/easy_install-LiOSu6/numpy-1.11.1rc1/setup.py", line 386, in <module>
      File "/tmp/easy_install-LiOSu6/numpy-1.11.1rc1/setup.py", line 339, in setup_package
      File "/tmp/easy_install-LiOSu6/numpy-1.11.1rc1/setup.py", line 140, in write_version_py
      File "/tmp/easy_install-LiOSu6/numpy-1.11.1rc1/setup.py", line 114, in get_version_info
    ImportError: Unable to import git_revision. Try removing numpy/version.py and the build directory before building.

The full build is here https://travis-ci.org/LCOGT/banzai/jobs/138989312 (See https://travis-ci.org/LCOGT/banzai/builds/138989303 for the full test suite).
The other tests pass without issue. Any assistance would be appreciated.

**Comment by pllim** [comment]
Maybe related to astropy/ci-helpers#98?

**Comment by bsipocz** [comment]
Yes, @pllim  is right, this was an issue with the new conda version and now should be fixed. Let us know in ci-helpers if you see any more problems.

**Comment by cmccully** [comment]
Ok. Thanks @pllim and @bsipocz. I will close this issue and open one in ci-helpers if need be.
