### ISSUE TITLE
Deprecate build_sphinx in favor of build_docs

### ISSUE THREAD

**Issue by adrn** [astropy/astropy-helpers#245]
We currently have two commands to build the documentation that do the same thing (or, will once #5156 is merged):

    python setup.py build_docs
    python setup.py build_sphinx

Right now `AstropyBuildDocs` subclasses `AstropyBuildSphinx` and is really just an alias.  As discussed in astropy/astropy#5156, we could switch this so that `AstropyBuildDocs` is the primary command and add a deprecation warning to `AstropyBuildSphinx`.

This issue is paired with astropy/astropy#5157 - a changelog entry needs to be added to the main astropy repo for the deprecation, but the actual code needs to be changed here.

**Comment by bsipocz** [comment]
This can be closed now.
