### ISSUE TITLE
Revise pytest-cov version requirement

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy-helpers#247]
pytest-cov got pinned to version 2.2.1 here https://github.com/astropy/astropy-helpers/pull/246#issuecomment-232698828

This is a reminder to check whether new versions work without the problem, and remove the version pinning.

**Comment by bsipocz** [comment]
Same issue is seen for pytest-cov 2.4 in #277

**Comment by astrofrog** [comment]
Looks like this was removed in the mean time
