### ISSUE TITLE
Astropy fails to build with numpy-dev as numpy is reloaded

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy-helpers#248]
Found in https://github.com/astropy/astropy/issues/5228, given the https://github.com/astropy/astropy/issues/5228#issuecomment-238652543 that this was likely due to astropy-helpers, specifically https://github.com/astropy/astropy-helpers/blob/master/astropy_helpers/utils.py#L74.

(edited to attribute comment correctly)

**Comment by MSeifert04** [comment]
Not sure but https://github.com/numpy/numpy/pull/7956 seems to (partially) adress the reason for the workaround function.

**Comment by mhvk** [comment]
Actually, this was fixed already by https://github.com/numpy/numpy/pull/7941, so closing
