### ISSUE TITLE
AstropyBuildSphinx TypeError

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy-helpers#250]
I started a new package from the package-template and got this error:

```
$ python setup.py $SETUP_CMD
/home/travis/miniconda/envs/test/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Freezing version number to healpix/version.py
running build_sphinx
creating /home/travis/build/cdeil/healpix/docs/_build
creating /home/travis/build/cdeil/healpix/docs/_build/doctrees
creating /home/travis/build/cdeil/healpix/docs/_build/html
/home/travis/build/cdeil/healpix/astropy_helpers/astropy_helpers/commands/build_sphinx.py:244: AstropyDeprecationWarning: The "build_sphinx" command is now deprecated. Use"build_docs" instead.
  '"build_docs" instead.', AstropyDeprecationWarning)
Traceback (most recent call last):
  File "setup.py", line 119, in <module>
    **package_info
  File "/home/travis/miniconda/envs/test/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/home/travis/miniconda/envs/test/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/home/travis/miniconda/envs/test/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/travis/build/cdeil/healpix/astropy_helpers/astropy_helpers/commands/build_sphinx.py", line 245, in run
    super(AstropyBuildSphinx, self).run()
TypeError: super() argument 1 must be type, not classobj
```

See https://github.com/cdeil/healpix/pull/2 where @astrofrog mentioned that I should file an issue here.

Some facts:
- Error only on Python 2, Python 3 works fine
- Error only for the deprecated `build_sphinx`, not the to-be used `build_docs` (`build_sphinx` is which is still the default in the package-template `.travis.yml` at this time)

I don't see the error when just running `python setup.py build_sphinx` on the package-template, but I de see it in this new project which basically is just a copy of the package-template files.

If someone has the energy / motivation to try and reproduce / fix this, you should be able to do it quickly by checking out the right commit corresponding to the travis-ci build linked to above and running `python2 setup.py build_sphinx`.

**Comment by saimn** [comment]
This is because the inherited classes (distutils' `Command`) does not inherit from `object`. So `super` doesn't work here.

**Comment by bsipocz** [comment]
I think this is fixed now with #251 merged, could you @cdeil confirm it?
On the other hand I don't see why you saw it at the first place, did you use an unreleased ``astropy-helpers`` to set up your package?

**Comment by cdeil** [comment]
@saimn @bsipocz - Thanks!

I don't have a version at hand.
I'm using `build_docs` now and everything works fine.

@bsipocz - You know I'll complain again if I find that something doesn't work properly in the future. :-)

**Comment by bsipocz** [comment]
Closing this then, and opening a separate issue in the ``package-template`` to make sure only versioned helpers are picked up, or recommend as such.
