### ISSUE TITLE
Pypi source URL broken

### ISSUE THREAD

**Issue by migueldvb** [astropy/astropy-helpers#253]
The URL for the latest release gives a 404: Not Found error

https://pypi.python.org/packages/source/a/astropy-helpers/astropy-helpers-1.2.tar.gz

**Comment by migueldvb** [comment]
The URL
https://files.pythonhosted.org/packages/source/a/astropy-helpers/astropy-helpers-1.2.tar.gz
is working fine though. We will use this for the [AUR package](https://aur.archlinux.org/packages/python-astropy-helpers/).

**Comment by bsipocz** [comment]
@migueldvb - Thanks for spotting this.
 We use the format ``https://pypi.io/packages/source/a/astropy-helpers/astropy-helpers-{{version}}.tar.gz`` for all our conda builds, I'll update the urls here for that, too.

**Comment by migueldvb** [comment]
Great, thanks! I think that  https://files.pythonhosted.org is also part of the new pypi site. It looks like these URLs will continue to work after the switch so that will help with making packages.
