### ISSUE TITLE
shutil.copy2 in build_ext

### ISSUE THREAD

**Issue by adrn** [astropy/astropy-helpers#255]
I'm running into a very strange issue on a Linux-based compute cluster. When trying to build one of my packages (based off of the package template), running `python setup.py build` dies almost immediately with:

```
running build
running build_py
running build_ext
error: [Errno 13] Permission denied: 'uncluster/_compiler.c'
```

I tracked it down and it looks like it is [this line](https://github.com/astropy/astropy-helpers/blob/master/astropy_helpers/commands/build_ext.py#L258) causing the problem. For some reason, `shutil.copy2()` fails on this system even though I have permissions from bash (`cp` and `cp -p` both work fine). Interestingly, if I change this to `shutil.copy()` instead, I don't get an error. 

So, I'm wondering why `shutil.copy2()` is used here instead of `shutil.copy()`?

**Comment by adrn** [comment]
Apparently the reason it fails on this particular system is that they are using [SELinux](https://en.wikipedia.org/wiki/Security-Enhanced_Linux)

**Comment by bsipocz** [comment]
I think @embray may remember why he chose ``shutil.copy2()`` over ``shutil.copy()``

**Comment by embray** [comment]
Hmm--are you building with some version of astropy-helpers installed as root?  Generally you shouldn't do that; it should be pulling in astropy-helpers to your local build directory and using it from there instead.  Otherwise I'm not clear on why `shutil.copy2` doesn't work, especially of `cp -p` does.

I don't remember if there's some specific reason to I used it though.

**Comment by embray** [comment]
Looks like @astrofrog actually added that line 9cd0701aae957601ad896b6a6423e7f6f50e433b but he's probably no more likely to remember...?

**Comment by astrofrog** [comment]
No real reason - I usually just use copy2 out of habit because I like to preserve the attributes, but that's not really needed here, so we can just switch to copy.

**Comment by pllim** [comment]
Drive-by PR #257.
