### ISSUE TITLE
Hide old versions on pypi

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy-helpers#256]
It looks like that we have the tools to make old versions hidden on pypi, but not using it regularly. I think it may also affects other packages in the astropy ecosystem beyond ``astropy-helpers``, so we may need to revise the release instructions, too.

```
class AstropyRegister(SetuptoolsRegister):
    """Extends the built in 'register' command to support a ``--hidden`` option
    to make the registered version hidden on PyPI by default.

    The result of this is that when a version is registered as "hidden" it can
    still be downloaded from PyPI, but it does not show up in the list of
    actively supported versions under http://pypi.python.org/pypi/astropy, and
    is not set as the most recent version.

    Although this can always be set through the web interface it may be more
    convenient to be able to specify via the 'register' command.  Hidden may
    also be considered a safer default when running the 'register' command,
    though this command uses distutils' normal behavior if the ``--hidden``
    option is omitted.
    """
```

![screen shot 2016-10-04 at 14 05 59](https://cloud.githubusercontent.com/assets/6788290/19075214/d6bb2a0e-8a3b-11e6-8c62-825116b7b544.png)

**Comment by embray** [comment]
Historically when I've done releases, I've always left up the latest release in each X.Y release series, just so it can easily be found by someone who for some reason is still on that release.  Though maybe it would be good to hide ones that are no longer supported.  From your screenshot I see some other releases aren't hidden that should be.

FWIW it is in the Astropy release procedures (step 19) which I guess has been forgotten a couple times: http://docs.astropy.org/en/stable/development/releasing.html#release-procedure

**Comment by embray** [comment]
Ok, I've marked 1.2rc1 and 1.0.6 as hidden.  I wasn't clear on if there's anything else to do here...

**Comment by bsipocz** [comment]
Thanks for the explanation and also for hiding those two, it looks much better now.
