### ISSUE TITLE
Warning about uknown section does not indicate where

### ISSUE THREAD

**Issue by MaxNoe** [astropy/astropy-helpers#260]
Building docmentation of ctapipe with the astropy helper functions, these warnings were issued:

```
/home/maxnoe/Uni/cta/ctapipe/astropy_helpers/astropy_helpers/sphinx/ext/docscrape.py:120: UserWarning: Unknown section Assumes
  warn("Unknown section %s" % key)
/home/maxnoe/Uni/cta/ctapipe/astropy_helpers/astropy_helpers/sphinx/ext/docscrape.py:120: UserWarning: Unknown section Note
  warn("Unknown section %s" % key)
/home/maxnoe/Uni/cta/ctapipe/astropy_helpers/astropy_helpers/sphinx/ext/docscrape.py:120: UserWarning: Unknown section Parameter
  warn("Unknown section %s" % key)
/home/maxnoe/Uni/cta/ctapipe/astropy_helpers/astropy_helpers/sphinx/ext/docscrape.py:120: UserWarning: Unknown section Return
  warn("Unknown section %s" % key)
```

But nowhere it is mentioned, where these warnings actually occured. This makes it really hard to debug these doc errors.

**Comment by pllim** [comment]
Temporary workaround: `grep` those mentioned section names in your RST files and see if anything is amiss (typo, etc).

**Comment by saimn** [comment]
It's something that should be adressed in numpydoc (https://github.com/numpy/numpydoc).
BTW, the numpydoc version bundled in Astropy should be updated.

**Comment by bsipocz** [comment]
This is upstream, and we have the latest numpydoc release, so not sure what else we could do.
