### ISSUE TITLE
[pytest] change in setup.cfg

### ISSUE THREAD

**Issue by justincely** [astropy/astropy-helpers#262]
My travis builds were spitting out warnings about the [pytest] section being deprecated.  I switched this to [tool:pytest] locally and that stopped the warnings.  

I don't know much about this, so figured i'd bring it up to those in the know here first - but i'm happy to issue a quick pull request with the changes if this is something needed.

**Comment by pllim** [comment]
This needs to happen in conjunction with astropy/astropy#5277
