### ISSUE TITLE
Appveyor picks up ci-helpers test

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy-helpers#265]
As @saimn points out in #261, appveyor tries to run the ci-helpers test, too rather than staying within the ``astropy-helpers`` subdir. This behaviour is new and started about a month ago. While the workaround in https://github.com/astropy/astropy-helpers/pull/261/commits/909b75b5030953fc4b98ed36db38f92cf044a08e works, it would be great to see what caused the changes.

Here are two runs of the same commit: 
 * https://ci.appveyor.com/project/Astropy/astropy-helpers/build/1.0.412
 * https://ci.appveyor.com/project/Astropy/astropy-helpers/build/1.0.419

**Comment by bsipocz** [comment]
OK, the difference is that the old build used pytest v2.9.2 while the new failing on is running v3.x

**Comment by bsipocz** [comment]
Weird, I don't see at all why the latest build passed just now: https://ci.appveyor.com/project/Astropy/astropy-helpers/build/1.0.420/job/a34a5g5nye8jo6ma

**Comment by bsipocz** [comment]
OK, sorry for the noise, this was actually a ci-helpers issue with pytest 3.x, that @astrofrog fixed today. However I still think that the ci-helpers test file shouldn't be picked up here.

**Comment by saimn** [comment]
@bsipocz - Note that for Travis the test command was already running tests only for the `astropy_helpers` directory: https://github.com/astropy/astropy-helpers/blob/master/.travis.yml#L66

**Comment by astrofrog** [comment]
Fundamentally, this is just because the test command is ``py.test`` rather than ``py.test astropy_helpers``. We should probably change it to the latter. The issue I fixed with ci-helpers was actually useful to identify packages that are running the ci-helpers tests by mistake ;)

**Comment by bsipocz** [comment]
@saimn - Fair enough. That case it was probably only a bug in pytest 2.9.2 to not pick it up.
