### ISSUE TITLE
Switch to use sphinx.ext.napoleon rather than numpydoc

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy-helpers#270]
It was raised in e.g. astropy/astropy#3974 that we should aim to switch to use the sphinx included napoleon rather than our numpydoc. However the transition will need a little bit of work, and also a deprecation period for our shipped numpydoc as affiliated packages use it.

**Comment by astrofrog** [comment]
Are we sure we want to do this? Is numpydoc deprecated or are these now competing efforts?

**Comment by pllim** [comment]
I switched over for my other projects. Never had problem. It is just changing the extension setting. One less dependency to worry about.

**Comment by astrofrog** [comment]
What is the minimum required version of sphinx for napoleon?

**Comment by pllim** [comment]
The doc says "new in 1.3"

**Comment by bsipocz** [comment]
I'm not sure we need to do this, but it was already suggested for the core.
It may be good if napoleon is a bit stricter about the syntax, but I don't
have anything against numpydoc

**Comment by eteq** [comment]
I know that I tried switching to napoleon once as an experiment (hacking with @Cadair, I belive?) and we got a bunch of sphinx warnings that were hard to track down.  But that *might* have been on an earlier version of napoleon or numpydocs?  Was probably ~6 months ago at least that I tried this...

**Comment by Cadair** [comment]
I recently did this swap for SunPy, it caused about 7 warnings, so there was some tweaking. This might obviously be worse for Astropy.

Even if the core package can not switch immediately I would be in favour of changing it in the package-template for new affiliated packages.

**Comment by bsipocz** [comment]
While I opened this issue following the astropy one, the answer to [@astrofrog's question above](https://github.com/astropy/astropy-helpers/issues/270#issuecomment-267353361) is not answered, and quick googling is not helping either. What are the pros and cons of using napoleon over numpydoc?

**Comment by astrofrog** [comment]
I don't feel strongly about this btw, but I can see the benefit of having one less dependency (since napoleon is built into sphinx)

**Comment by Cadair** [comment]
I think they are not competing efforts, my main motivation for change would be one less dep / no need to maintain the astropy fork of numpydoc.

**Comment by astrofrog** [comment]
Moved this issue to https://github.com/astropy/sphinx-astropy/issues/5
