### ISSUE TITLE
name 'wl' is not defined

### ISSUE THREAD

**Issue by xueyingtianhua** [astropy/astropy-helpers#281]
I try to run the example but the terminal showed there are something wrong."
Traceback (most recent call last):
  File "test.py", line 27, in <module>
    integral=True)
  File "/Users/~/anaconda/lib/python3.5/site-packages/higal_sedfitter/fit.py", line 175, in fit_modified_blackbody_tofiles
    outheader = fits.getheader(target_files[wl])
NameError: name 'wl' is not defined.
I need some help.

**Comment by bsipocz** [comment]
@xueyingtianhua - I'm afraid this isn't the repository that causes you problem, ``astropy-helpers`` are a helpers package aimed for package maintainers. You probably need to report the issue to the ``higal_sedfitter`` package.

Could you please tell us more details, e.g. what are you trying to run?
