### ISSUE TITLE
Installing astropy_helpers should probably not need numpy

### ISSUE THREAD

**Issue by Cadair** [astropy/astropy-helpers#291]
This is a very edge case thing, but doing "pip install astropy_helpers" should, in theory not need numpy. Only installing a package using astropy_helpers has a numpy requirement.

This is pretty low priority to fix, but I thought I would leave it here so it doesn't get completely forgotten about.

ping @eteq

**Comment by eteq** [comment]
Agreed that this makes sense.  In practice I think it's a low-priority mainly because most (all?) use cases of astropy-helpers are packages that require numpy anyway.

But that could change if someone starts saying they want to use the helpers with something that's not numpy-required...

**Comment by andamian** [comment]
Hi,

We have a few astronomy-related projects that don't depend on either astropy nor numpy (Virtual Observatory software). For consistency reasons, we've decided to follow the astropy framework. I've noticed that the installs now depend on numpy through astropy_helpers but the packages already released on pypi don't seem to be affected (do they package and use an older version of astropy_helpers?)

So, for us, if this affects the package after it is released to users then it is an issue. If the problem is contained to the development environment then that would be only slightly more inconvenient as 'python setup.py test' had already had dependencies on astropy and numpy. 

Best of course is to not have these dependencies at all.

**Comment by eteq** [comment]
@bsipocz @astrofrog - any thoughts on the feasibility of this?  I haven't really looked closely enough at the machinery to say just how hard a task it is to be to change the numpy linking options to be "opt-in"?

**Comment by bsipocz** [comment]
in theory numpy is not listed in setup.py in ``install_requires`` or in ``requires``, so unless one uses a functionality that requires numpy, it should work? this is purely theoretical argument, I have never tried it.

**Comment by andamian** [comment]
FYI, there is also a dependency on astropy:

"File "mypackage/__init__.py", line 10, in <module>
    from ._astropy_init import *
  File "mypackage/_astropy_init.py", line 118, in <module>
    from astropy.config.configuration import (
ImportError: No module named astropy.config.configuration

In my project, I've patched it by moving the import from line 118 down to just before it's being used (line 130) and that work. Can this make it upstream into the repo?

**Comment by bsipocz** [comment]
@andamian @Cadair  - Yes, some of the functionality of the package depends on astropy, but the original issue here was about install time numpy dependency, which I think is indeed should not be required (and probably is not atm?).

**Comment by pllim** [comment]
@andamian , the file you mentioned is in https://github.com/astropy/package-template/blob/master/packagename/_astropy_init.py . That is a package template. In that case, it uses Astropy for testing, and Astropy uses Numpy. That is beyond the scope of `astropy_helpers`, no?

**Comment by bsipocz** [comment]
@pllim - I agree with you here. Also I think the original issue can be closed or needs to be reworded, as ``pip install astropy-helpers`` works for me:
```
bsipocz@tegla2:~$ pip list|grep numpy
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
bsipocz@tegla2:~$ pip list|grep astropy
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
astropy-helpers (1.3)
bsipocz@tegla2:~$ pip install astropy-helpers
The directory '/Users/bsipocz/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/bsipocz/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting astropy-helpers
  Downloading astropy-helpers-1.3.tar.gz (136kB)
    100% |████████████████████████████████| 143kB 3.9MB/s 
Installing collected packages: astropy-helpers
  Running setup.py install for astropy-helpers ... done
Successfully installed astropy-helpers-1.3
```

**Comment by andamian** [comment]
@pllim and @bsipocz, thanks for looking into this. You are probably right in the sense that I probably posted to the wrong flow - I'm an astropy newbie still trying to figure out this thing. I'm going to open the issue with package-template.

I think however that the issues are related. I imagine that one of the goals for creating all the astropy related infrastructure packages (astropy_helpers, package-template) was to avoid the dependency on astropy (and numpy) when not necessary, as in my case.

**Comment by Cadair** [comment]
@bsipocz huh I am sure I did `pip install astropy-helpers` the other day and it started pulling (and compiling) numpy. Can't reproduce now though.
