### ISSUE TITLE
setup.py sdist should ignore system umask for release

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy-helpers#294]
File permission will be set accordingly to the system-wide umask when one creates a release source distribution with ``python setup.py build sdist``.  
While a note is definitely needed to be added about this to the release procedure documentation (giving a workaround for the problem), I think it would be more productive to get the permission issue fixed in the helpers/setup.py.

Treating this as a bug unless finding a good reason for this behaviour is a feature.

Related issue: https://github.com/astropy/astropy/issues/5912

**Comment by cdeil** [comment]
I know that there are some tools to check if a conda package is OK:
* https://conda.io/docs/bdist_conda.html
* https://github.com/conda/conda-verify

I don't know of something similar for sdists (but haven't looked for that yet) that does e.g. the file permission check.

In any case, it seems to me that this is something that could be done in a Python script that is maintained in the astropy or astropy-helpers repo, and then the release checklist gets an extra point to run this tool to run the check on the files before uploading them to PyPI.

**Comment by bsipocz** [comment]
Thanks @cdeil for the tips. I feel any such scripts could live in http://github.com/astropy/astropy-tools

**Comment by cdeil** [comment]
With a quick Google search I didn't find anything for `sdist` checks. I'm a bit surprised there is no tooling for this already, so I asked if here: http://stackoverflow.com/questions/43886777/is-there-a-tool-to-check-python-distribution-sdist-files
