### ISSUE TITLE
Add --help support for command-line options supported by ah_bootstrap

### ISSUE THREAD

**Issue by embray** [astropy/astropy-helpers#31]
As suggested in #27, I guess it would be good if ah_bootstrap.py integrated somewhat with distutils' command-line parsing so that, for example, command-line options used by ah_bootstrap can be reported to the user when they run `setup.py --help`.

**Comment by bsipocz** [comment]
I think `python setup.py --help-commands` does this to an extent, and otherwise, realistically speaking don't think any more effort will be spent on it, so I'm closing the issue.
