### ISSUE TITLE
Typo in ah_bootstrap.py : _AHBoostrapSystemExit

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy-helpers#311]
While trying to reproduce #302 I (briefly, hopefully never again) looked at `aH_bootstrap.py` with my Python editor PyCharm, and it pointed out these bugs that also show up with pyflakes:
```
$ pyflakes ah_bootstrap.py 
ah_bootstrap.py:705: undefined name '_AHBoostrapSystemExit'
ah_bootstrap.py:766: undefined name '_AHBoostrapSystemExit'
ah_bootstrap.py:895: undefined name 'args'
ah_bootstrap.py:898: undefined name 'args'
```
Is this dead code that should be removed or should this be fixed?

There's also these
```
ah_bootstrap.py:100: 'setuptools.py31compat' imported but unused
ah_bootstrap.py:887: redefinition of unused 'log' from line 131
```
which deal with Python 2.6 and 3.1 and is just code that can probably be removed?

Presumably no-one supports Python 3.1 any more and it would be OK to drop that support from `astropy-helpers`, no?

**Comment by bsipocz** [comment]
I think ``setuptools.py31compat`` is still needed as it introduces the ``TemporaryDirectory`` class that is missing from python 2.7

**Comment by bsipocz** [comment]
@cdeil - Are you interested in opening the fix, or shall I? Sadly this is still not solving the original problem.

**Comment by bsipocz** [comment]
Went ahead and opened these in #312 and #313
