### ISSUE TITLE
edit_on_github should only work for master

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy-helpers#316]
When people are opening PRs using the ``edit_on_github`` feature it most usually causes a bigger mess than it solves as most usually they open the PR against the wrong branch (see the latest issue here against "stable": https://github.com/astropy/astropy/pull/6172)

I suggest to try to disable it for anything but the "latest" rtd version. I think the other option of making it point always to the master version will be more confusing, as the page may have changed significantly since the given version one tries to edit.

The other workaround could be to train astrobot to pick up all PRs that are not against master and comment on them prior merge. 

cc @eteq @astrofrog

**Comment by bsipocz** [comment]
Having a closer look, it seems to be that pointing the ``edit_on_github`` link always to master is easy and only needs the modification in ``docs/conf.py`` in the astropy repo.

**Comment by astrofrog** [comment]
Moved this issue to https://github.com/astropy/sphinx-astropy/issues/7
