### ISSUE TITLE
Tests fail with Astropy LTS

### ISSUE THREAD

**Issue by nmearl** [astropy/astropy-helpers#324]
Using the astropy lts release to run tests fails due to the `test` command failing during the `setup.py` call. This seems to be because the lts version does not contain a module named `command`

```python
>>> import astropy
>>> astropy.__version__
u'1.0.13'
>>> from astropy.tests.command import AstropyTest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named command
```

which means that the `test` command fails due an import error [here](https://github.com/astropy/astropy-helpers/blob/master/astropy_helpers/commands/test.py#L20).

```bash
$ $MAIN_CMD $SETUP_CMD
Freezing version number to ./mosviz/version.py
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help
error: The 'test' command requires the astropy package to be installed and importable.
```

The doc string suggests the command *should* fall back to some backwards compatible implementation, but it seems that whatever that was was [removed](https://github.com/astropy/astropy-helpers/commit/1e7a4e6a699af6c7edbadd9fa867d5e909cbc4e1) as per #307.

Currently this prevents travis builds from completing successfully.

**Comment by pllim** [comment]
But Astropy 1.0.x would have been locked to an older release of `astropy-helpers` as well. :thinking:

**Comment by astrofrog** [comment]
Ah but the relevant version of the helpers is that of the affiliated package not of astropy.

Astropy 2.0 is being released today, so let's hold off for a day or so to see if this is still an issue.

**Comment by bsipocz** [comment]
Which version of the helpers are you using? Could you point to a failing build?
E.g. #307 is not included in the 2.0 release, so you shouldn't run into any issues related to it.

I'm about to update ci-helpers, so the LTS will point to 2.0.x from now on. You can still test against 1.0.x but then need to specify it.

**Comment by nmearl** [comment]
Hm, I think I've tracked it down. The used cookiecutter to create the project template, but I already had an initialized git repository, so I avoided having cookiecutter do itself.

This meant that I added the submodule manually, but it looks like I forgot to checkout the 1.3.1 release branch (it was using the 3.0.dev version).

Thanks for your attention, all.

**Comment by bsipocz** [comment]
btw 2.0 is out for the helpers, too. 

We will open PRs for the affiliates to update to that later this evening. If you have a list of packages, I can add them to the list (they don't need to be official affiliates).
