### ISSUE TITLE
Bare excepts in ah_bootstrap.py

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-helpers#328]
In my campaign to remove bare excepts (`except:`) in Ginga, I encountered 3 such things in `ah_bootstrap.py`. I don't see any reason you cannot use `except Exception:` there, i.e., do you really need to capture keyboard interrupt? Just want to make sure I can really change them to the latter. Thanks.

**Comment by bsipocz** [comment]
I recall some comments about this by Erik B, can dig them up in the evening to see whether they are still relevant. Anyway, I think it's rather useful to add these ah related files to the exclude list of pycodestyle/flake8 just as all other external bundles.

**Comment by MSeifert04** [comment]
There's rarely a use for catching `SystemExit`, `GeneratorExit` or a `KeyboardInterrupt`. But even then we probably should make the intent clearer by using `except BaseException`.

**Comment by bsipocz** [comment]
There is only one of the bare ones are remaining, so I would call this issue addressed.
