### ISSUE TITLE
Deprecate or remove requires_2to3 support

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy-helpers#333]
This is probably a discussion for the in-person coordination meeting, but I think we should consider removing support for ``requires_2to3`` (which allows 2to3 to be disabled on a per-subpackage basis) once we make sure that no affiliated packages are using it. If we make this decision, then I think the following things can be removed:

* The custom ``build`` command (``AstropyBuildPy``), because the main purpose of this command is to deal with the 2to3 option and also to separate build directories for different Python versions even for pure-Python packages, which was only needed because the Python 2 and 3 source code could be different.

* The custom ``install`` and ``install_lib`` commands (``AstropyInstall`` and ``AstropyInstallLib``) - these were only needed because we were customizing the build location with ``AstropyBuildPy``, but should no longer be needed once we use standard build directories.

* Some code in ``setup_helpers.py`` related to this option.

Overall, the main benefit would be to go back to not providing custom build, install, and install_lib commands. In general I think we should always be striving to use the standard mechanisms for package maintenance whenever possible.

Maybe we could set a deadline of 3.0 for this, and warn affiliated package maintainers so that they adjust their code base to be 2 and 3-compatible? (which would be a good thing anyway). Note that if they don't want to do that yet, they can simply avoid updating to a more recent astropy-helpers.

**Comment by pllim** [comment]
Someone told me once that the fastest way to learn how to swim is to get thrown in the water... :wink: 

So :+1:

**Comment by bsipocz** [comment]
Big 👍 from me. As astropy core 3.0 becomes python3 only, it makes sense that the helpers 3.0 also becomes more strict. 

One point to discuss in the meeting is that I think it would be extremely useful to include the full changelog into the auto-update PR messages, so noone can blame us braking their packages...

**Comment by astrofrog** [comment]
So just to be clear, 2to3 would continue to work if we removed any mention of it in astropy-helpers. What would *not* work is repositories that have ``use_2to3=True`` set *and* also disable ``2to3`` on a subpackage basis with ``setup_package.py`` (this is what astropy-helpers adds). Based on some mining of GitHub repositories, I've identified the following repositories as ones that would be affected by this change:

http://github.com/fred3m/astro-toyz
http://github.com/MSeifert04/nddata
http://github.com/pkaminski/sample
http://github.com/Reviewable/demo
http://github.com/spacetelescope/cdrizzle
http://github.com/spacetelescope/drizzle
http://github.com/spacetelescope/spherical_geometry
http://github.com/spacetelescope/stsynphot_refactor
http://github.com/alexrudy/Cauldron
http://github.com/alexrudy/Zeeko
http://github.com/spacetelescope/asdf

All other repos that use the helpers either don't use ``use_2to3``, or use it but don't have any ``requires_2to3`` in setup_package.py that returns False.

If we do go ahead with this, I think the steps should be:

* Notify the owners of the above repos by pinging their username in this issue
* Make the changes in astropy-helpers and eventually release 3.0 of the helpers
* When we auto-update the helpers, for repositories that have ``use_2to3=True`` we could add a custom message in the PR description with a warning that says ``2to3`` is no longer supported in the helpers

**Comment by pllim** [comment]
Oh, dear. I see quite a few of STScI repos. I'll open issues for those now.

**Comment by astrofrog** [comment]
Based on the discussion at the coordination meeting, I think it's fine to remove this - packages can always opt to not upgrading to astropy-helpers 3.0, which will support Python 3 only anyway.
