### ISSUE TITLE
Remove python2 support

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy-helpers#337]
In coordination with astropy core 3.0, we can/should remove any python2 related code from here.

**Comment by MSeifert04** [comment]
How will that affect affiliated packages? As soon as the helpers-submodule is updated the affiliated package won't support Python 2.x anymore? Or is it just that manual installation/test running/etc won't be supported on Python 2.x?

**Comment by astrofrog** [comment]
@MSeifert04 - we'll still release astropy-helpers bug fix releases on the 2.0.x branch, i.e. astropy-helpers 2.0.x is also an LTS I think (at least that's how we've operated before). So for packages that want to continue supporting Python 2, they should update to the latest 2.0.x but not 3.x helpers. We can probably figure out heuristically which version to update to for the auto-updating.

**Comment by MSeifert04** [comment]
So affiliated packages that want to support astropy LTS (2.0.x) and Python 2.7 shouldn't update helpers to 3.x as long as they want to support LTS and Python 2?

Sorry, I really don't know where the helpers are used *exactly* but I assume it could be really weird with CI.

**Comment by astrofrog** [comment]
Affiliated packages that still want to work on Python 2 in any way (which includes working with the astropy LTS)  shouldn't update to helpers 3.x but can update to future helpers 2.0.x releases. Let's turn it around - packages should only update to helpers 3.x if they are dropping Python 2 support. They can still support the 2.x LTS release on Python 3 only (and in that case using helpers 3.x is fine).

**Comment by MSeifert04** [comment]
Thank you for the explanation @astrofrog !

**Comment by astrofrog** [comment]
We should definitely mention this in the README for this repo once this work is done.
