### ISSUE TITLE
Split theme out into separate package

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy-helpers#338]
At the coordination meeting in NY there were no objections to splitting the sphinx theme out into a separate package. I think that for consistency with other plugin names like ``sphinx-gallery``, ``sphinx-automodapi``, and theme package names like ``sphinx-rtd-theme`` this package should be called ``sphinx-astropy-theme``. We also discussed that the cleanest way to get people to install all the plugins required would be to make a ``sphinx-astropy`` metapackage.

I've stated a repo here for the theme:

https://github.com/astropy/sphinx-astropy-theme

Does anyone volunteer to take a stab at this?

**Comment by Cadair** [comment]
https://github.com/Cadair/astropy-sphinx-theme

**Comment by Cadair** [comment]
I did it a long time ago...

**Comment by astrofrog** [comment]
Great! Could you open a PR to the new repo to add the latest files? (since things might have changed a little since then)

**Comment by saimn** [comment]
Could be worth doing a proper extraction from git to keep the history ? It's not hard to do, and always good to know when and by who things were done.

**Comment by astrofrog** [comment]
@saimn @Cadair - I redid this preserving all commits and including some of @Cadair's new commits: https://github.com/astropy/sphinx-astropy-theme - does this seem ok to you? The filtering process only kept one non-trivial merge commit, but I don't think we need to actually keep the other merge commits?

**Comment by Cadair** [comment]
Lgtm!

**Comment by saimn** [comment]
Sounds great !
