### ISSUE TITLE
Add helper function to determine whether -fopenmp flag can be used

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy-helpers#345]
It would be useful to have a helper function that can determine whether ``-fopenmp`` can be included in the list of flags for C/Cython extensions (since Cython makes it easy to make loops parallel). We could then start using OpenMP when available for affiliated packages and even astropy core.

**Comment by drdavella** [comment]
@astrofrog was this fixed by #346?

**Comment by astrofrog** [comment]
Yep!
