### ISSUE TITLE
Failure to install on py3.6

### ISSUE THREAD

**Issue by keflavich** [astropy/astropy-helpers#364]
We're now seeing issue #359 on python 3.6 also:

https://travis-ci.org/radio-astro-tools/spectral-cube/jobs/330117493#L828

**Comment by astrofrog** [comment]
@keflavich - are you still seeing this?

**Comment by keflavich** [comment]
Not with 2.0.3, I believe,  but my issues are not yet entirely resolved.

https://github.com/radio-astro-tools/spectral-cube/pull/460

**Comment by astrofrog** [comment]
I think the issue should be fixed now, but please re-open if not
