### ISSUE TITLE
Possible issues with API compatibility in dependencies

### ISSUE THREAD

**Issue by drdavella** [astropy/astropy-helpers#376]
Consider the following scenario: I have an affiliated package **A** which depends on other affiliated packages **B** and **C**. The packages **B** and **C** are listed in `install_requires` in my `setup.py` file. Now, in a clean environment, I run a command like `setup.py install` on package **A**.

In this particular scenario, it appears to be the case that the instance of `astropy_helpers` that is packaged with **A** will be used to build the dependencies **B** and **C** as well. This would make sense if, as I suspect, `setuptools` is running the entire build/installation process from within a single Python process. The `astropy_helpers` package is first imported by package **A**'s `setup.py`, and so it will be the one that is used for every subsequent import of `astropy_helpers`, even those within the `setup.py` files belonging to packages **B** and **C**.

The problem is that the dependencies **B** and **C** probably came from PyPI, and so they may not have the latest and greatest version of `astropy_helpers`. Since package **A** is being built and installed from source, it probably does have a later version of `astropy_helpers`.

In certain cases, this can cause build failures. Consider the submodule `astropy_helpers.test_helpers`, which was previously deprecated, and was recently removed. If dependency **B** makes reference to `test_helpers` in its `setup.py` file, it will fail to build if package **A** has the latest version of `astropy_helpers`.

"So what?", you may rightly ask. There are plenty of workarounds, like pip requirements files or conda environments where all dependencies are installed before running a command like `setup.py install`. That's fair, and I'm not sure what the right solution is anyway. At the very least I just wanted to make a record of this issue since I am confident that someone else will run into it at some point in the future.

**Comment by astrofrog** [comment]
This is solved by moving away from astropy-helpers and using pyproject.toml for extension-helpers ([APE 17](https://github.com/astropy/astropy-APEs/blob/master/APE17.rst))
