### ISSUE TITLE
Removal of 2to3 has unwanted side effect

### ISSUE THREAD

**Issue by olebole** [astropy/astropy-helpers#378]
I just realized that astropy-helpers removed 2to3 support with the notice 

> Packages wishing to keep Python 2 support should NOT update to this version.

In Debian, I however use not the astropy-helpers version provided with the package but the actual one provided with the system (and this is actually what `[ah_bootstrap] auto_use = False` is for). This has the side effect that packages that need 2to3 cannot be built anymore. Could this decision be rethought?

This was discovered with asdf: spacetelescope/asdf#447 (luckily, 2to3 is not required there...)

**Comment by bsipocz** [comment]
What about shipping only the 2.0.x releases in debian then, or ship both but if a package requires 2to3, then use the 2.0.x version? 
Afaik we discourage the usage of 2to3 anyway, so affiliates shouldn't really use it.

**Comment by astrofrog** [comment]
I agree with @bsipocz - packages that require 2to3 should simply use astropy-helpers 2.0.x, which we continue to support.

**Comment by olebole** [comment]
I just checked all packages in Debian that build-depend on astropy-helpers: The only other package with `use_2to3=True` is  [drizzle](https://github.com/spacetelescope/drizzle). But this package also has
```
def requires_2to3():
    return False
```
in [`drizzle/setup_package.py`](https://github.com/spacetelescope/drizzle/blob/8197da17c8d4b18f9d6cb236f1b96cf7d6017793/drizzle/setup_package.py#L12-L13). For the moment it will therefore probably cause the same problems as asdf that the latter is ignored (and 2to3 is silently applied), but this is easy to fix by changing `use_2to3` in [`setup.py`](https://github.com/spacetelescope/drizzle/blob/8197da17c8d4b18f9d6cb236f1b96cf7d6017793/setup.py#L121) (right?).

So, after rethinking, the removal is fine for me.
IMO it would be still good if there would be some error like "2to3 is not supported anymore" if these features are still accessed. Silently dropping them leads to problems that may be hard to detect or catch (see spacetelescope/asdf#447 as an example).

**Comment by bsipocz** [comment]
I'm closing this issue based on the comment above, and now as it's less and less relevant by packages moving away from python2 support, and it only affected 2 to begin with.

Please feel free to reopen if you think otherwise.

**Comment by olebole** [comment]
We also dropped all Python 2 packages associated with astropy in Debian. That is the right way to do.
