### ISSUE TITLE
ah_bootstrap.py should give a better message about non-Python 3 support

### ISSUE THREAD

**Issue by embray** [astropy/astropy-helpers#380]
Apologies if this has already come up elsewhere, though I didn't see a ticket for it.  Installing Astropy 3.0 in Python 2 resulted in:

```
$ pip install astropy
Collecting astropy
  Downloading astropy-3.0.tar.gz (8.0MB)
    100% |████████████████████████████████| 8.0MB 134kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-m82yXL/astropy/setup.py", line 8, in <module>
        import ah_bootstrap
      File "ah_bootstrap.py", line 923, in <module>
        BOOTSTRAPPER = _Bootstrapper.main()
      File "ah_bootstrap.py", line 227, in main
        bootstrapper.run()
      File "ah_bootstrap.py", line 325, in run
        dist = method()
      File "ah_bootstrap.py", line 393, in get_local_directory_dist
        upgrade = self._do_upgrade(dist)
      File "ah_bootstrap.py", line 572, in _do_upgrade
        return self._do_download(version=upgrade.version)
      File "ah_bootstrap.py", line 557, in _do_download
        raise Exception(msg.format(DIST_NAME, source, repr(e)))
    Exception: Error retrieving astropy-helpers from PyPI:
    ImportError('No module named builtins',)
```

It would be nice if there were a `try/except` around this initial import, and upon failure an error message specifically that Astropy 3.0 doesn't support Python 2.

**Comment by astrofrog** [comment]
@embray - just out of curiosity, how recent is your pip? On recent versions of pip, it shouldn't even fetch the astropy 3.0 tar file to begin with since we define ``python_requires``. I agree we should also have an error message in ``ah_bootstrap.py`` though.

**Comment by bsipocz** [comment]
No, I can't recall a ticket for it, but remember that we tried to put in a nicer error message, and 3.0 shouldn't not even be picked up as `python_requires` is set to `'3.5'`.

Do you by any chance have an old pip version?

**Comment by bsipocz** [comment]
(oh, @astrofrog, you're always quicker than I ;) ). Anyway, I think this feature (PEP 345) needs pip 9.0+, but I also agree that we better get it fixed in `ah_bootstrap.py`, too.

**Comment by astrofrog** [comment]
By the way, I think we shouldn't try...except ``builtins`` but rather have a more explicit check on ``sys.version_info`` at the top of ``ah_bootstrap``, just in case we get rid of the ``builtins`` import in future.
