### ISSUE TITLE
Running test suite leaves v/cache/nodeids file

### ISSUE THREAD

**Issue by cczhu** [astropy/astropy-helpers#401]
For `baseband`, which is built with the Astropy package template and currently using astropy-helpers v2.0.7, we're currently stumped on an issue (mhvk/baseband#255) where doing
```
import baseband
baseband.test()
```
in the Python interpreter leaves a residual `v/cache/nodeids` file in the interpreter's working directory.  This occurs in a barebones Python 2 or 3 virtualenv with only `baseband`, `pytest-astropy` and their dependencies installed, but no residual files are left if I downgrade to `pytest==3.5.0`.  No files are left behind when `python setup.py test` is called in the Baseband source code repository, either.

Is this a known issue with astropy-helpers, or is it caused by pytest itself?  Is there a way to automatically delete any residual files generated by `baseband.test()`?

Thanks for your help!

**Comment by pllim** [comment]
`cache/nodeids` is a `pytest` thing; https://docs.pytest.org/en/latest/cache.html . Not sure about the behaviour change in `pytest>3.5`. @drdavella , have you encountered this?

**Comment by saimn** [comment]
I think the pytest cache plugin used to create a `v/` directory which was renamed to `.cache` and then to `.pytest_cache`. But I also see now a `v/` directory in my astropy clone, so I tried `pytest --cache-clear` and it deleted my whole directory content ! :sob: 

I was about to report this to pytest, but hey I think it is because of some astropy pytest plugin ! The plugin that manages the Astropy cache has a `cache_dir` option, which could probably conflict with the same setting in pytest. That would explain why `v/` and a `README.md` file created by pytest go in the root directory instead of `.pytest_cache/`. cc @drdavella

**Comment by saimn** [comment]
So yeah this is because of `astropy/tests/plugins/config.py`.
Before running its `pytest_addoption` there is a `cache_dir` option from pytest:
```
(Pdb++) parser._inidict['cache_dir']
('cache directory path.', None, '.pytest_cache')
```
This is overridden by the plugin, and this option is set to `''`:
```
(Pdb++) l
 58  	    config_dir = item.config.getini('config_dir')
 59  	    cache_dir = item.config.getini('cache_dir')
 60  	    __import__('pdb').set_trace()
 61  	
 62  	    # Command-line options can override, however
 63  ->	    config_dir = item.config.getoption('config_dir') or config_dir
 64  	    cache_dir = item.config.getoption('cache_dir') or cache_dir
 65  	
 66  	    # We can't really use context managers directly in py.test (although
 67  	    # py.test 2.7 adds the capability), so this may look a bit hacky
 68  	    if config_dir:
(Pdb++) item.config.getini('cache_dir')
''
(Pdb++) item.config.getoption('cache_dir')
```
So pytest use the current directory as cache...

**Comment by drdavella** [comment]
Is it the case that this only happens when using `pytest` directly, and not when running through `setup.py test`?

**Comment by saimn** [comment]
It seems to be only with pytest, with `--trace-config` I can see a ` cachedir: .` line, but not with `setup.py test`.

**Comment by pllim** [comment]
And from the report above, `package.test()` has the same behavior as running `pytest` directly?

**Comment by pllim** [comment]
Also maybe move this over to `astropy/astropy`?

**Comment by drdavella** [comment]
Can this be closed now?
