### ISSUE TITLE
get_np_include_path() undefined 

### ISSUE THREAD

**Issue by jamienoss** [astropy/astropy-helpers#405]
@drdavella  Regression from #404 

Causes CircleCI and AppVeryor tests to fail ([example](https://ci.appveyor.com/project/Astropy/astropy/build/1.0.11803#L319)).

Looks like you forgot to import and/or define the function ``get_np_include_path()`` ([src](https://github.com/astropy/astropy-helpers/blob/master/astropy_helpers/commands/build_ext.py#L296)).

**Comment by drdavella** [comment]
Ah yep, that's a bug.

**Comment by drdavella** [comment]
I'm fairly surprised this wasn't caught by CI here.

**Comment by jamienoss** [comment]
>I'm fairly surprised this wasn't caught by CI here.

Right. Hmmm...

I think this is [the test](https://travis-ci.org/astropy/astropy-helpers/jobs/428179423) that you added for that PR. It obviously passed. Wonder what that implies?

**Comment by drdavella** [comment]
Actually the fact that that particular test passes implies that the change had the intended effect: things don't crash and burn when `numpy` is not available.

But I would have expected this code path to have been executed by one of the other tests.

**Comment by jamienoss** [comment]
Ok, I see now, I hadn't looked at #404 properly.

>But I would have expected this code path to have been executed by one of the other tests.

Me too. Hmmmm

**Comment by saimn** [comment]
Really weird, `get_np_include_path` was already used in this function before #404, which just moved this line.

**Comment by saimn** [comment]
Huhu, when moving the line you changed  `get_numpy_include_path` to `get_np_include_path` ! :stuck_out_tongue:

**Comment by drdavella** [comment]
@saimn yeah that was stupid of me 🙄 . Anyway, I thought it would have been used *somewhere* in the test suite??
