### ISSUE TITLE
Support for pytest>=3.7

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-helpers#411]
Is what @drdavella did in astropy/astropy#7890 also needed here for this?

https://github.com/astropy/astropy-helpers/blob/58fea18455c235f740d75f21469be92426555371/astropy_helpers/conftest.py#L21-L28

**Comment by drdavella** [comment]
This should not be necessary here. It was only necessary in Astropy proper because there we have a module for backwards compatibility named `pytest_plugins.py`. The specific module name `pytest_plugins` makes `pytest` very unhappy, but we don't have that problem here.

**Comment by pllim** [comment]
Oh, ok. Thanks for the clarifications!
