### ISSUE TITLE
Consider removing _adjust_compiler

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy-helpers#417]
The ``_adjust_compiler`` method provides a way of determining whether a 'broken' compiler is being used, and if so, to change it on-the-fly. In practice, this has only ever been used once, for a specific Mac version of gcc 4.2. In addition, while this compiler was broken for astropy.wcs, it doesn't mean it was for other packages.

In the spirit of trying to remove unnecessary functionality from astropy-helpers, I'd like to suggest that we remove this - first, this is an old issue and it's unlikely anyone is using this compiler now (even more so since most people install from conda/wheels anyway), and because if this happens in future, I feel like it makes more sense to document as a known issue than do magic with swapping compilers on-the-fly.

**Comment by pllim** [comment]
I agree with removing it.

**Comment by bsipocz** [comment]
I agree to remove it if we can, but disagree with "even more so since most people install from conda/wheels anyway", most of the helpers stuff is needed by us maintainers who work with and install from the source code.

**Comment by hamogu** [comment]
+1 to removing it.

**Comment by astrofrog** [comment]
Let's move the discussion to https://github.com/astropy/astropy-helpers/pull/421

**Comment by astrofrog** [comment]
Done in #421
