### ISSUE TITLE
Consider if version helper is still needed

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-helpers#420]
https://github.com/spacetelescope/relic was written by @jhunkeler and it does automatic versioning through `git tag` functionality. I used it for some of my projects and find it rather convenient. Posting it here for your consideration.

**Comment by bsipocz** [comment]
I think this is an excellent topic to bring up at the meeting.

**Comment by hamogu** [comment]
I've used versioneer (https://pypi.org/project/versioneer/) in several package for this purpose and found it to work well, too.

**Comment by astrofrog** [comment]
I looked into versioneer recently and it looked like it hadn't had any repo activity for a couple of years unfortunately :-/

**Comment by saimn** [comment]
Another option is setuptools_scm, it looks pretty good and is developped by the pypa team:
https://github.com/pypa/setuptools_scm/

**Comment by Cadair** [comment]
closed by APE 17 (it isn't)
