### ISSUE TITLE
Namespace path issues

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy-helpers#429]
For some reason when I do ``import astropy_helpers`` on my machine, it works (even though it's not installed) and ``astropy_helpers.__path__`` returns:

```
_NamespacePath(['/Users/tom/Projects/Glue/STScI/mosviz/astropy_helpers', '/Users/tom/Dropbox/Code/Astropy/reproject/astropy_helpers', '/Users/tom/Dropbox/Code/Astropy/regions/astropy_helpers', '/Users/tom/Dropbox/Code/Astropy/astropy-timeseries/astropy_helpers', '/Users/tom/Projects/Glue/STScI/cubeviz/astropy_helpers', '/Users/tom/Dropbox/Code/Astropy/astropy/astropy_helpers'])
```

The package isn't actually usable, but the import works, which is weird...

**Comment by pllim** [comment]
Did you import it from the source checkout root or something? I cannot reproduce (within Miniconda).

```
ModuleNotFoundError
```

**Comment by bsipocz** [comment]
Could it be that it's being picked up for the repos where one did a `pip install -e .`? I see a similar list as @astrofrog, and all the paths point to a repo checkout, never a "proper" install in side-packages.
