### ISSUE TITLE
TST: sphinx job fails on Travis CI

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-helpers#436]
Example log: https://travis-ci.org/astropy/astropy-helpers/jobs/477217814
```
Exception occurred:
  File ".../sphinx_automodapi/automodsumm.py", line 136, in run
    self.warnings = []
```

This shows up in `master` and all recent PRs.

**Comment by astrofrog** [comment]
Fixed - just released sphinx-automodapi 0.10
