### ISSUE TITLE
How to use and install IMEXAM on IDL? 

### ISSUE THREAD

**Issue by AaronLig** [astropy/astropy-helpers#459]
Would like to use IMEXAM as an external library to IDL 8.7.2. Does it possible? How and where to download the IMEXAM package? Should I need to install a specific IMEXAM version adaptable to IDL? - Thank you very much for your help. - Gil Moretto (CRAL/CNRS/France)

**Comment by pllim** [comment]
I think this is the wrong repo for this question. Python port of IMEXAM is at https://github.com/spacetelescope/imexam .

**Comment by sosey** [comment]
I'll comment here, incase someone else finds this issue, that the python imexam package isn't meant to be used with IDL at all, only in a python environment. Feel free to ask more questions over on the imexam git page pey-lian referenced above though! :)
