### ISSUE TITLE
openmp_enabled.py should be a temp file rather than in the repo

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy-helpers#461]
Running tests dumps a `openmp_enabled.py` file in the main repo directory. It should rather go into a temporary file that gets deleted after the tests are run.

Content:
```
# Autogenerated by 's setup.py on 2019-04-23 00:18:30

def is_openmp_enabled():
    """
    Determine whether this package was built with OpenMP support.
    """
    return False`
```

**Comment by pllim** [comment]
Would adding it to `.gitignore` be sufficient?

**Comment by bsipocz** [comment]
The tests should not litter nevertheless.
