### ISSUE TITLE
astropy-helpers should respect python_requires

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy-helpers#462]
Matplotlib stopped supporting python3.5 in their new release (it's not a release just yet, but 3.1rc1). This causes failure on our CI here for the python3.5 build.

However this our own fault as the machinery here doesn't respect the `python_requires` in mpl's setup.py.

@tacaswell kindly digged up that the offending lines are likely  https://github.com/astropy/astropy-helpers/blob/b17db72b5b8b039ffb42a767cc8311f6f1c77b49/astropy_helpers/commands/build_sphinx.py#L58-L60 

```
from setuptools import Distribution
dist = Distribution()
eggs = dist.fetch_build_eggs('sphinx-astropy')
```

I'll work this around for our CI to get the RC out sooner rather than later, but it would be great if we fix this before the actual release (and it may need to be backported, to LTS, too).

**Comment by astrofrog** [comment]
I think this is because setuptools doesn’t recognise python_requires. Not sure if we can easily use pip instead though.

**Comment by bsipocz** [comment]
Or give up on seamlessly install sphinx-astropy and ask packages to explicitly list it (as they need to do it with pytest, sphinx, etc.)
