### ISSUE TITLE
Prereleases should not be picked up automatically

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy-helpers#463]
In our CI we pick up docs dependencies and egg install them. 

However even then we should not pick up pre-releases.

Related build (that fails because of #462): https://travis-ci.org/astropy/astropy-helpers/jobs/523215037#L1194

**Comment by astrofrog** [comment]
I think this is because setuptools doesn’t understand prereleases are special. Maybe we need to make sure the dependencies are pip installed.

**Comment by bsipocz** [comment]
Yes, and I suppose it won't change any time soon in setuptools: https://github.com/pypa/setuptools/issues/855
