### ISSUE TITLE
remove deprecation for build_sphinx  command

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy-helpers#481]
`build_sphinx` is still the standard way for sphinx setuptools integration. I strongly feel that we should remove the deprecation warning and keep it along with the convenience `build_docs`.

**Comment by pllim** [comment]
Wasn't there a big discussion when we decided to go with `build_docs`? @eteq always says there should only be one way to do things. 🤔

**Comment by bsipocz** [comment]
Yes, but then `build_sphinx` is the canonical way to do it.

**Comment by eteq** [comment]
A bit of googling implies to me that `build_docs` is still only used pretty much only in the astropy community, whereas `build_sphinx` is the standard elsewhere.  So on that basis I think I'm 👍 to this.  To truly get to the "only one way to do it" at this point I think we would need a bigger break like astropy/astropy-APEs#52 ...

(Out-of-band @pllim revealed that it was me that argued for `build_docs` in the first place?  But @Cadair agreed so it must have been a good idea at the time 😜 )

**Comment by pllim** [comment]
Just gonna xref some history that I dug up related to this during the coworking hour today:

* astropy/astropy#5157
* astropy/astropy#3924
* astropy/astropy-helpers#161

Personally, I am okay with @bsipocz 's idea to remove the warning.

**Comment by Cadair** [comment]
`import this`...

**Comment by bsipocz** [comment]
The removal of deprecation warning has been merged in, feel free to reopen this issue if you prefer a bigger cleanup.
