### ISSUE TITLE
Deprecation warning from bundled astropy sphinx theme

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy-helpers#483]
There is a deprecation warning issues when using the 2.0.x branch of the helpers coming from the sphinx theme. Not sure whether we should act on it here or leave it be. @astrofrog - what do you think?

```
/Users/bsipocz/munka/devel/reproject/astropy_helpers/astropy_helpers/sphinx/themes/bootstrap-astropy/layout.html:15: RemovedInSphinx30Warning: To modify script_files in the theme is deprecated. Please insert a <script> tag directly in your theme instead.
  <div class="topbar">
```

**Comment by astrofrog** [comment]
There's no harm in fixing it, and I think this might be causing the astropy core LTS docs build to fail, so I've done it in https://github.com/astropy/astropy-helpers/pull/493
