### ISSUE TITLE
[3.2.1] Tests are missing in pypi package

### ISSUE THREAD

**Issue by olebole** [astropy/astropy-helpers#491]
When using the latest version (3.2.1) from pypi, the subdirectory `astropy_helpers/tests` is missing, so that the package can't be tested.

**Comment by pllim** [comment]
Was it ever successful? There is a `prune astropy_helpers/tests` directive in the manifest and it was added 5 years ago.

**Comment by olebole** [comment]
Ahh, good that you ask that ;-) Last time, I took a 3.2 prerelease from github for the RC test and found the tests (…and had to explicitly disable the tests; see #477). Checking our old build logs shows that indeed that tests were never executed before. And since this package has (hopefully) a limited lifetime, getting them (and getting them running) is probably not worth the effort.
So, I'd propose to just close this.

Generally, I am wondering whether I should move from pip to github for the package. This also would make testing prereleases and development snapshots easier.
