### ISSUE TITLE
Add the possibility of adding a 2to3: False option to setup.cfg

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy-helpers#52]
It would be nice to be able to globally disable the use of 2to3 in a package rather than having to go through ``setup_package.py``.

**Comment by embray** [comment]
This is kind of a moot point now since we're not using 2to3 anymore, and not many affiliated-packages are either.  As for setup.cfg this will be covered by #2 which will include a setup.cfg for `use_2to3` (as d2to1 does--I'm thinking of using d2to1 itself, or at least its ancestor).
