### ISSUE TITLE
Build Cython C sources as prereq of sdist

### ISSUE THREAD

**Issue by embray** [astropy/astropy-helpers#53]
Somehow I was convinced this was already done, to ensure that C files compiled from Cython sources are included in the sdist.  But apparently that isn't working.  Something to do.

**Comment by bsipocz** [comment]
sorry for closing, I was mistaken that this issue was in the package-template repo.

**Comment by astrofrog** [comment]
As we approach end of life for astropy-helpers, we will never fix this so I will go ahead and close.
