### ISSUE TITLE
Populate README/other documentation

### ISSUE THREAD

**Issue by eteq** [astropy/astropy-helpers#7]
I realize the priority now is getting things working, but I thought I would put this in as a reminder... Currently the README is empty, and there's not really any documentation in this repository about astropy-helpers, what it is, how it works, etc.  That's definitely worth doing once APE4 is actually merged.

**Comment by cdeil** [comment]
It's been over a year since the last comment here ...
Any chance to get some documentation for `astropy-helpers`?
(currently I'm wondering if setuptools is / should be a dependency for packages that use astropy-helpers, see #202)

**Comment by embray** [comment]
No, setuptools should not be a dependency.

**Comment by kelle** [comment]
The documentation for this package needs to be improved. For a "typical" person using the package template and wanting to make an astropy affiliate package, it's unclear what astropy-helpers does and how to decide if a package should use it or not.
For example, if the package uses cython, astropy-helpers is needed. However, for packages that are mostly "simple" code, astropy-helpers is not needed. More information is needed to help contributors decide whether or not to use astropy-helpers.

**Comment by bsipocz** [comment]
@kelle - astropy-helpers provides much more than the cython stuff. The customized pytest and sphinx setups makes it worth for simple packages to opt in, too.

**Comment by kelle** [comment]
It would be helpful if the things it helps with were described, at least briefly, in the README.

**Comment by astrofrog** [comment]
![didit](https://media.giphy.com/media/26u4eMNSMWydF0v8A/source.gif)

(in #416)
