### ISSUE TITLE
Move test stuff to astropy-helpers if there's a need for it outside astropy-dependents

### ISSUE THREAD

**Issue by eteq** [astropy/astropy-helpers#73]
In APE4 and the current master, the test runner and related framework are *not* in  `astropy-helpers`, but rather in `astropy`.  The justification from @embray in APE4 is that the tests have to be at runtime, so it makes sense to leave it in `astropy` given that affiliated packages will need it at runtime anyway.

But while working on #72 I realized an issue with that: the test runner and test command are now in separate packages, so they can't be kept in sync.  More generally, it's really confusing to figure out how they interplay when they are in different packages.  So maybe we should just move all the testing stuff to `astropy-helpers` too?

cc @astrofrog

**Comment by eteq** [comment]
@embray @astrofrog - I wanted to report an oddity related to this issue that I just encountered.  Halotools (which uses the package template) was getting strange errors on travis while trying to run their test suite.  It turns out this is because they were using numpy v1.8 for the main part of the test suite, and the conda packages for astropy are numpy 1.9 *only* after v4.1.  So they were getting astropy v4.1, which is incompatible with the current astropy helpers (due to the addition of the ``repeat`` keyword for the test runner).  Having all of the test stuff in the helpers would get around such versioning issues.

**Comment by embray** [comment]
Interesting...I'll have to take a closer look in a bit.  But I feel like when I added the `repeat` keyword I updated the test runner so that it wouldn't use unsupported arguments.  In other words, I thought I made a specific point of addressing this kind of issue.

**Comment by embray** [comment]
@eteq Aha.  It appears that [the workaround I added for this](https://github.com/astropy/astropy-helpers/commit/1068e26) was only added to the v0.4.x branch on astropy-helpers, and is not in master.  I guess the thinking there was that I was going to do something "better" later.  But this solution is still better than nothing so I better copy it over...

**Comment by eteq** [comment]
@embray - ok, that sounds good for that particular issue.

The main point of this issue is still relevant because it would have prevented this in the first place.  But I guess it's not particularly more urgent now than before...

**Comment by embray** [comment]
It's just too bad I didn't copy the change over--then it would've just worked like I planned =D

**Comment by embray** [comment]
Oops--this was addressed by #184 and related.  The test stuff is all back in astropy itself.  It could still be split out of astropy too if some package wanted to use it without depending on astropy.  But in that case it should be its own entity separate from both astropy and astropy-helpers.
