### ISSUE TITLE
Add generic support for submodules

### ISSUE THREAD

**Issue by eteq** [astropy/astropy-helpers#74]
It came up in astropy/photutils#132 that it might be nice to be able to have git submodules available in an affiliated package.  However, the bar for use of submodules is very high: for good or for ill, most people I talk about it are afraid of them/don't understand how to use them.

Fortunately, `ah_bootstrap` has solved this problem already, as has the `ipython` `setup.py` : just update the submodules as part of the setup process.It would be great to put machinery like this in the `astropy-helpers`, so that affiliated packages and astropy can start using it. 

@embray, do you thing the `ah_bootstrap` code can be translated fairly easily into a `setup.py` command to do submodule updating  (a la ipython)? Or would it be better to lift some of it from ipython, or start from scratch?  (or I suppose "not do it at all" is another option)

**Comment by keflavich** [comment]
I'd like to chime in again now that I understand what `ah_bootstrap.py` does: YES, I want this feature!  I have a submodule included in pyspeckit that doesn't clone or load by default, which leads to tests (which I have in a submodule) not loading.  

Astroquery will probably want this too, eventually - for now, it doesn't need any submodules, though.

**Comment by astrofrog** [comment]
How about we make it a command-line option for ``setup.py`` then specific projects can turn it on by default in the ``setup.cfg`` if needed?

**Comment by embray** [comment]
I don't want to add any more zany command-line options if it can be avoided, but as I mentioned earlier I think additional submodules could be listed in setup.cfg.

**Comment by embray** [comment]
@keflavich Note, you can use `git clone --recursive` to clone a repo *and* initialize all its submodules.  I recommend just making an alias for that.

**Comment by keflavich** [comment]
@embray - I can, but other people cloning my repositories won't by default.  And someone installing from source but not from a clone won't get access to the submodule at all.  Right?

**Comment by embray** [comment]
>  And someone installing from source but not from a clone won't get access to the submodule at all

If by which you mean a source tarball or something, if you want the submodule included with it you'll need to put the right entries in the MANIFEST.in file.  I would instead lean on the side of *not* doing that and instead have the submodule (if it is a Python package, at least) listed as a dependency instead.  But there are some cases where that's not preferable (I, for example, would prefer not to actually bundle astropy-helpers with the source tarball, but enough people preferred having it that I had no choice but to bend on that).

**Comment by cdeil** [comment]
By now I also have a use for this feature.

We have a submodule in  https://github.com/cta-observatory/ctapipe and I'm adding https://github.com/gammapy/gammapy-extra as a submodule to https://github.com/gammapy/gammapy now, which includes data used by the tests and Sphinx docs, and other things.

I see that @mdboom made a PR to implement this: #155

Is there anyone that knows `setup.py`, `astropy-helpers` and `git submodule` well and continue that PR?

**Comment by astrofrog** [comment]
Since we're moving away from astropy-helpers as a sub-module given that APE 17 is merged, I'm going to close this.
